/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConversationHistory } from '../models';
// @ts-ignore
import type { ConversationRequest } from '../models';
// @ts-ignore
import type { ConversationResponse } from '../models';
// @ts-ignore
import type { EmotionAnalysis } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * ConversationsApi - axios parameter creator
 * @export
 */
export const ConversationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Analyze emotion in text.
         * @summary Analyze Emotion
         * @param {number} userId 
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost: async (userId: number, text: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost', 'userId', userId)
            // verify required parameter 'text' is not null or undefined
            assertParamExists('analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost', 'text', text)
            const localVarPath = `/api/v1/conversations/{user_id}/analyze-emotion`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (text !== undefined) {
                localVarQueryParameter['text'] = text;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a specific conversation message.
         * @summary Delete Message
         * @param {number} userId 
         * @param {number} messageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete: async (userId: number, messageId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete', 'userId', userId)
            // verify required parameter 'messageId' is not null or undefined
            assertParamExists('deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete', 'messageId', messageId)
            const localVarPath = `/api/v1/conversations/{user_id}/messages/{message_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)))
                .replace(`{${"message_id"}}`, encodeURIComponent(String(messageId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get conversation history for a user.
         * @summary Get Conversation History
         * @param {number} userId 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConversationHistoryApiV1ConversationsUserIdHistoryGet: async (userId: number, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getConversationHistoryApiV1ConversationsUserIdHistoryGet', 'userId', userId)
            const localVarPath = `/api/v1/conversations/{user_id}/history`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Process a conversation message and generate a response.
         * @summary Process Conversation
         * @param {ConversationRequest} conversationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processConversationApiV1ConversationsProcessPost: async (conversationRequest: ConversationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationRequest' is not null or undefined
            assertParamExists('processConversationApiV1ConversationsProcessPost', 'conversationRequest', conversationRequest)
            const localVarPath = `/api/v1/conversations/process`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(conversationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConversationsApi - functional programming interface
 * @export
 */
export const ConversationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConversationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Analyze emotion in text.
         * @summary Analyze Emotion
         * @param {number} userId 
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost(userId: number, text: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmotionAnalysis>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost(userId, text, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConversationsApi.analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a specific conversation message.
         * @summary Delete Message
         * @param {number} userId 
         * @param {number} messageId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete(userId: number, messageId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete(userId, messageId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConversationsApi.deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get conversation history for a user.
         * @summary Get Conversation History
         * @param {number} userId 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConversationHistoryApiV1ConversationsUserIdHistoryGet(userId: number, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConversationHistory>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConversationHistoryApiV1ConversationsUserIdHistoryGet(userId, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConversationsApi.getConversationHistoryApiV1ConversationsUserIdHistoryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Process a conversation message and generate a response.
         * @summary Process Conversation
         * @param {ConversationRequest} conversationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processConversationApiV1ConversationsProcessPost(conversationRequest: ConversationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConversationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.processConversationApiV1ConversationsProcessPost(conversationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConversationsApi.processConversationApiV1ConversationsProcessPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ConversationsApi - factory interface
 * @export
 */
export const ConversationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConversationsApiFp(configuration)
    return {
        /**
         * Analyze emotion in text.
         * @summary Analyze Emotion
         * @param {ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost(requestParameters: ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<EmotionAnalysis> {
            return localVarFp.analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost(requestParameters.userId, requestParameters.text, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a specific conversation message.
         * @summary Delete Message
         * @param {ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete(requestParameters: ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete(requestParameters.userId, requestParameters.messageId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get conversation history for a user.
         * @summary Get Conversation History
         * @param {ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConversationHistoryApiV1ConversationsUserIdHistoryGet(requestParameters: ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConversationHistory> {
            return localVarFp.getConversationHistoryApiV1ConversationsUserIdHistoryGet(requestParameters.userId, requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Process a conversation message and generate a response.
         * @summary Process Conversation
         * @param {ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processConversationApiV1ConversationsProcessPost(requestParameters: ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConversationResponse> {
            return localVarFp.processConversationApiV1ConversationsProcessPost(requestParameters.conversationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ConversationsApi - interface
 * @export
 * @interface ConversationsApi
 */
export interface ConversationsApiInterface {
    /**
     * Analyze emotion in text.
     * @summary Analyze Emotion
     * @param {ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost(requestParameters: ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<EmotionAnalysis>;

    /**
     * Delete a specific conversation message.
     * @summary Delete Message
     * @param {ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete(requestParameters: ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * Get conversation history for a user.
     * @summary Get Conversation History
     * @param {ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    getConversationHistoryApiV1ConversationsUserIdHistoryGet(requestParameters: ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConversationHistory>;

    /**
     * Process a conversation message and generate a response.
     * @summary Process Conversation
     * @param {ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApiInterface
     */
    processConversationApiV1ConversationsProcessPost(requestParameters: ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConversationResponse>;

}

/**
 * Request parameters for analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost operation in ConversationsApi.
 * @export
 * @interface ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest
 */
export interface ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost
     */
    readonly userId: number

    /**
     * 
     * @type {string}
     * @memberof ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost
     */
    readonly text: string
}

/**
 * Request parameters for deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete operation in ConversationsApi.
 * @export
 * @interface ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest
 */
export interface ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest {
    /**
     * 
     * @type {number}
     * @memberof ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete
     */
    readonly userId: number

    /**
     * 
     * @type {number}
     * @memberof ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete
     */
    readonly messageId: number
}

/**
 * Request parameters for getConversationHistoryApiV1ConversationsUserIdHistoryGet operation in ConversationsApi.
 * @export
 * @interface ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest
 */
export interface ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest {
    /**
     * 
     * @type {number}
     * @memberof ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGet
     */
    readonly userId: number

    /**
     * 
     * @type {number}
     * @memberof ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGet
     */
    readonly limit?: number

    /**
     * 
     * @type {number}
     * @memberof ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGet
     */
    readonly offset?: number
}

/**
 * Request parameters for processConversationApiV1ConversationsProcessPost operation in ConversationsApi.
 * @export
 * @interface ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest
 */
export interface ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest {
    /**
     * 
     * @type {ConversationRequest}
     * @memberof ConversationsApiProcessConversationApiV1ConversationsProcessPost
     */
    readonly conversationRequest: ConversationRequest
}

/**
 * ConversationsApi - object-oriented interface
 * @export
 * @class ConversationsApi
 * @extends {BaseAPI}
 */
export class ConversationsApi extends BaseAPI implements ConversationsApiInterface {
    /**
     * Analyze emotion in text.
     * @summary Analyze Emotion
     * @param {ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApi
     */
    public analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost(requestParameters: ConversationsApiAnalyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPostRequest, options?: RawAxiosRequestConfig) {
        return ConversationsApiFp(this.configuration).analyzeEmotionApiV1ConversationsUserIdAnalyzeEmotionPost(requestParameters.userId, requestParameters.text, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a specific conversation message.
     * @summary Delete Message
     * @param {ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApi
     */
    public deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete(requestParameters: ConversationsApiDeleteMessageApiV1ConversationsUserIdMessagesMessageIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return ConversationsApiFp(this.configuration).deleteMessageApiV1ConversationsUserIdMessagesMessageIdDelete(requestParameters.userId, requestParameters.messageId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get conversation history for a user.
     * @summary Get Conversation History
     * @param {ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApi
     */
    public getConversationHistoryApiV1ConversationsUserIdHistoryGet(requestParameters: ConversationsApiGetConversationHistoryApiV1ConversationsUserIdHistoryGetRequest, options?: RawAxiosRequestConfig) {
        return ConversationsApiFp(this.configuration).getConversationHistoryApiV1ConversationsUserIdHistoryGet(requestParameters.userId, requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Process a conversation message and generate a response.
     * @summary Process Conversation
     * @param {ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConversationsApi
     */
    public processConversationApiV1ConversationsProcessPost(requestParameters: ConversationsApiProcessConversationApiV1ConversationsProcessPostRequest, options?: RawAxiosRequestConfig) {
        return ConversationsApiFp(this.configuration).processConversationApiV1ConversationsProcessPost(requestParameters.conversationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

