/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * ExpensesApi - axios parameter creator
 * @export
 */
export const ExpensesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get cost breakdown by service, provider, and model.
         * @summary Get Cost Breakdown
         * @param {number | null} [userId] Filter by user ID
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCostBreakdownApiV1ExpensesCostBreakdownGet: async (userId?: number | null, days?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/expenses/cost-breakdown`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get usage breakdown by model.
         * @summary Get Model Usage
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getModelUsageApiV1ExpensesModelsGet: async (days?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/expenses/models`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get recent API usage records.
         * @summary Get Recent Usage
         * @param {number | null} [userId] Filter by user ID
         * @param {number} [limit] Number of records to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecentUsageApiV1ExpensesRecentUsageGet: async (userId?: number | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/expenses/recent-usage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get total costs and usage statistics.
         * @summary Get Total Costs
         * @param {number | null} [userId] Filter by user ID
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTotalCostsApiV1ExpensesTotalCostsGet: async (userId?: number | null, days?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/expenses/total-costs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get detailed usage statistics.
         * @summary Get Usage Stats
         * @param {number | null} [userId] Filter by user ID
         * @param {string | null} [serviceType] Filter by service type
         * @param {string | null} [provider] Filter by provider
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsageStatsApiV1ExpensesUsageStatsGet: async (userId?: number | null, serviceType?: string | null, provider?: string | null, days?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/expenses/usage-stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (serviceType !== undefined) {
                localVarQueryParameter['service_type'] = serviceType;
            }

            if (provider !== undefined) {
                localVarQueryParameter['provider'] = provider;
            }

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExpensesApi - functional programming interface
 * @export
 */
export const ExpensesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExpensesApiAxiosParamCreator(configuration)
    return {
        /**
         * Get cost breakdown by service, provider, and model.
         * @summary Get Cost Breakdown
         * @param {number | null} [userId] Filter by user ID
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCostBreakdownApiV1ExpensesCostBreakdownGet(userId?: number | null, days?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCostBreakdownApiV1ExpensesCostBreakdownGet(userId, days, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpensesApi.getCostBreakdownApiV1ExpensesCostBreakdownGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get usage breakdown by model.
         * @summary Get Model Usage
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getModelUsageApiV1ExpensesModelsGet(days?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getModelUsageApiV1ExpensesModelsGet(days, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpensesApi.getModelUsageApiV1ExpensesModelsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get recent API usage records.
         * @summary Get Recent Usage
         * @param {number | null} [userId] Filter by user ID
         * @param {number} [limit] Number of records to return
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecentUsageApiV1ExpensesRecentUsageGet(userId?: number | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecentUsageApiV1ExpensesRecentUsageGet(userId, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpensesApi.getRecentUsageApiV1ExpensesRecentUsageGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get total costs and usage statistics.
         * @summary Get Total Costs
         * @param {number | null} [userId] Filter by user ID
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTotalCostsApiV1ExpensesTotalCostsGet(userId?: number | null, days?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTotalCostsApiV1ExpensesTotalCostsGet(userId, days, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpensesApi.getTotalCostsApiV1ExpensesTotalCostsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get detailed usage statistics.
         * @summary Get Usage Stats
         * @param {number | null} [userId] Filter by user ID
         * @param {string | null} [serviceType] Filter by service type
         * @param {string | null} [provider] Filter by provider
         * @param {number} [days] Number of days to analyze
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsageStatsApiV1ExpensesUsageStatsGet(userId?: number | null, serviceType?: string | null, provider?: string | null, days?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsageStatsApiV1ExpensesUsageStatsGet(userId, serviceType, provider, days, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExpensesApi.getUsageStatsApiV1ExpensesUsageStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExpensesApi - factory interface
 * @export
 */
export const ExpensesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExpensesApiFp(configuration)
    return {
        /**
         * Get cost breakdown by service, provider, and model.
         * @summary Get Cost Breakdown
         * @param {ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCostBreakdownApiV1ExpensesCostBreakdownGet(requestParameters: ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getCostBreakdownApiV1ExpensesCostBreakdownGet(requestParameters.userId, requestParameters.days, options).then((request) => request(axios, basePath));
        },
        /**
         * Get usage breakdown by model.
         * @summary Get Model Usage
         * @param {ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getModelUsageApiV1ExpensesModelsGet(requestParameters: ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getModelUsageApiV1ExpensesModelsGet(requestParameters.days, options).then((request) => request(axios, basePath));
        },
        /**
         * Get recent API usage records.
         * @summary Get Recent Usage
         * @param {ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecentUsageApiV1ExpensesRecentUsageGet(requestParameters: ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getRecentUsageApiV1ExpensesRecentUsageGet(requestParameters.userId, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Get total costs and usage statistics.
         * @summary Get Total Costs
         * @param {ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTotalCostsApiV1ExpensesTotalCostsGet(requestParameters: ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getTotalCostsApiV1ExpensesTotalCostsGet(requestParameters.userId, requestParameters.days, options).then((request) => request(axios, basePath));
        },
        /**
         * Get detailed usage statistics.
         * @summary Get Usage Stats
         * @param {ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsageStatsApiV1ExpensesUsageStatsGet(requestParameters: ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.getUsageStatsApiV1ExpensesUsageStatsGet(requestParameters.userId, requestParameters.serviceType, requestParameters.provider, requestParameters.days, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExpensesApi - interface
 * @export
 * @interface ExpensesApi
 */
export interface ExpensesApiInterface {
    /**
     * Get cost breakdown by service, provider, and model.
     * @summary Get Cost Breakdown
     * @param {ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getCostBreakdownApiV1ExpensesCostBreakdownGet(requestParameters?: ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * Get usage breakdown by model.
     * @summary Get Model Usage
     * @param {ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getModelUsageApiV1ExpensesModelsGet(requestParameters?: ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * Get recent API usage records.
     * @summary Get Recent Usage
     * @param {ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getRecentUsageApiV1ExpensesRecentUsageGet(requestParameters?: ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * Get total costs and usage statistics.
     * @summary Get Total Costs
     * @param {ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getTotalCostsApiV1ExpensesTotalCostsGet(requestParameters?: ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * Get detailed usage statistics.
     * @summary Get Usage Stats
     * @param {ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApiInterface
     */
    getUsageStatsApiV1ExpensesUsageStatsGet(requestParameters?: ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

}

/**
 * Request parameters for getCostBreakdownApiV1ExpensesCostBreakdownGet operation in ExpensesApi.
 * @export
 * @interface ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest
 */
export interface ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest {
    /**
     * Filter by user ID
     * @type {number}
     * @memberof ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGet
     */
    readonly userId?: number | null

    /**
     * Number of days to analyze
     * @type {number}
     * @memberof ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGet
     */
    readonly days?: number
}

/**
 * Request parameters for getModelUsageApiV1ExpensesModelsGet operation in ExpensesApi.
 * @export
 * @interface ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest
 */
export interface ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest {
    /**
     * Number of days to analyze
     * @type {number}
     * @memberof ExpensesApiGetModelUsageApiV1ExpensesModelsGet
     */
    readonly days?: number
}

/**
 * Request parameters for getRecentUsageApiV1ExpensesRecentUsageGet operation in ExpensesApi.
 * @export
 * @interface ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest
 */
export interface ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest {
    /**
     * Filter by user ID
     * @type {number}
     * @memberof ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGet
     */
    readonly userId?: number | null

    /**
     * Number of records to return
     * @type {number}
     * @memberof ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGet
     */
    readonly limit?: number
}

/**
 * Request parameters for getTotalCostsApiV1ExpensesTotalCostsGet operation in ExpensesApi.
 * @export
 * @interface ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest
 */
export interface ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest {
    /**
     * Filter by user ID
     * @type {number}
     * @memberof ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGet
     */
    readonly userId?: number | null

    /**
     * Number of days to analyze
     * @type {number}
     * @memberof ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGet
     */
    readonly days?: number
}

/**
 * Request parameters for getUsageStatsApiV1ExpensesUsageStatsGet operation in ExpensesApi.
 * @export
 * @interface ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest
 */
export interface ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest {
    /**
     * Filter by user ID
     * @type {number}
     * @memberof ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGet
     */
    readonly userId?: number | null

    /**
     * Filter by service type
     * @type {string}
     * @memberof ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGet
     */
    readonly serviceType?: string | null

    /**
     * Filter by provider
     * @type {string}
     * @memberof ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGet
     */
    readonly provider?: string | null

    /**
     * Number of days to analyze
     * @type {number}
     * @memberof ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGet
     */
    readonly days?: number
}

/**
 * ExpensesApi - object-oriented interface
 * @export
 * @class ExpensesApi
 * @extends {BaseAPI}
 */
export class ExpensesApi extends BaseAPI implements ExpensesApiInterface {
    /**
     * Get cost breakdown by service, provider, and model.
     * @summary Get Cost Breakdown
     * @param {ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public getCostBreakdownApiV1ExpensesCostBreakdownGet(requestParameters: ExpensesApiGetCostBreakdownApiV1ExpensesCostBreakdownGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).getCostBreakdownApiV1ExpensesCostBreakdownGet(requestParameters.userId, requestParameters.days, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get usage breakdown by model.
     * @summary Get Model Usage
     * @param {ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public getModelUsageApiV1ExpensesModelsGet(requestParameters: ExpensesApiGetModelUsageApiV1ExpensesModelsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).getModelUsageApiV1ExpensesModelsGet(requestParameters.days, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get recent API usage records.
     * @summary Get Recent Usage
     * @param {ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public getRecentUsageApiV1ExpensesRecentUsageGet(requestParameters: ExpensesApiGetRecentUsageApiV1ExpensesRecentUsageGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).getRecentUsageApiV1ExpensesRecentUsageGet(requestParameters.userId, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get total costs and usage statistics.
     * @summary Get Total Costs
     * @param {ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public getTotalCostsApiV1ExpensesTotalCostsGet(requestParameters: ExpensesApiGetTotalCostsApiV1ExpensesTotalCostsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).getTotalCostsApiV1ExpensesTotalCostsGet(requestParameters.userId, requestParameters.days, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get detailed usage statistics.
     * @summary Get Usage Stats
     * @param {ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExpensesApi
     */
    public getUsageStatsApiV1ExpensesUsageStatsGet(requestParameters: ExpensesApiGetUsageStatsApiV1ExpensesUsageStatsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ExpensesApiFp(this.configuration).getUsageStatsApiV1ExpensesUsageStatsGet(requestParameters.userId, requestParameters.serviceType, requestParameters.provider, requestParameters.days, options).then((request) => request(this.axios, this.basePath));
    }
}

