/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FactCreate } from '../models';
// @ts-ignore
import type { FactSearch } from '../models';
// @ts-ignore
import type { FactSearchResult } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { MemoryContext } from '../models';
// @ts-ignore
import type { MemoryStats } from '../models';
// @ts-ignore
import type { ProfileSummary } from '../models';
// @ts-ignore
import type { ProfileSummaryCreate } from '../models';
// @ts-ignore
import type { UserFact } from '../models';
/**
 * MemoryApi - axios parameter creator
 * @export
 */
export const MemoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Store a new fact for a user.
         * @summary Create Fact
         * @param {FactCreate} factCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFactApiV1MemoryFactsPost: async (factCreate: FactCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'factCreate' is not null or undefined
            assertParamExists('createFactApiV1MemoryFactsPost', 'factCreate', factCreate)
            const localVarPath = `/api/v1/memory/facts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(factCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a specific fact.
         * @summary Delete Fact
         * @param {number} factId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFactApiV1MemoryFactsFactIdDelete: async (factId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'factId' is not null or undefined
            assertParamExists('deleteFactApiV1MemoryFactsFactIdDelete', 'factId', factId)
            const localVarPath = `/api/v1/memory/facts/{fact_id}`
                .replace(`{${"fact_id"}}`, encodeURIComponent(String(factId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Generate or update user profile summary.
         * @summary Generate Profile Summary
         * @param {ProfileSummaryCreate} profileSummaryCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateProfileSummaryApiV1MemorySummariesGeneratePost: async (profileSummaryCreate: ProfileSummaryCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profileSummaryCreate' is not null or undefined
            assertParamExists('generateProfileSummaryApiV1MemorySummariesGeneratePost', 'profileSummaryCreate', profileSummaryCreate)
            const localVarPath = `/api/v1/memory/summaries/generate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profileSummaryCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get complete memory context for a user.
         * @summary Get Memory Context
         * @param {number} userId 
         * @param {string | null} [query] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemoryContextApiV1MemoryContextUserIdGet: async (userId: number, query?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getMemoryContextApiV1MemoryContextUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/memory/context/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get memory statistics for a user.
         * @summary Get Memory Stats
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemoryStatsApiV1MemoryStatsUserIdGet: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getMemoryStatsApiV1MemoryStatsUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/memory/stats/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all profile summaries for a user.
         * @summary Get Profile Summaries
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProfileSummariesApiV1MemorySummariesUserIdGet: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getProfileSummariesApiV1MemorySummariesUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/memory/summaries/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all facts for a user.
         * @summary Get User Facts
         * @param {number} userId 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string | null} [category] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserFactsApiV1MemoryFactsUserIdGet: async (userId: number, limit?: number, offset?: number, category?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserFactsApiV1MemoryFactsUserIdGet', 'userId', userId)
            const localVarPath = `/api/v1/memory/facts/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Search for relevant facts using semantic similarity.
         * @summary Search Facts
         * @param {FactSearch} factSearch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFactsApiV1MemoryFactsSearchPost: async (factSearch: FactSearch, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'factSearch' is not null or undefined
            assertParamExists('searchFactsApiV1MemoryFactsSearchPost', 'factSearch', factSearch)
            const localVarPath = `/api/v1/memory/facts/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(factSearch, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MemoryApi - functional programming interface
 * @export
 */
export const MemoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MemoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Store a new fact for a user.
         * @summary Create Fact
         * @param {FactCreate} factCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createFactApiV1MemoryFactsPost(factCreate: FactCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserFact>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createFactApiV1MemoryFactsPost(factCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.createFactApiV1MemoryFactsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a specific fact.
         * @summary Delete Fact
         * @param {number} factId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFactApiV1MemoryFactsFactIdDelete(factId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteFactApiV1MemoryFactsFactIdDelete(factId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.deleteFactApiV1MemoryFactsFactIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Generate or update user profile summary.
         * @summary Generate Profile Summary
         * @param {ProfileSummaryCreate} profileSummaryCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateProfileSummaryApiV1MemorySummariesGeneratePost(profileSummaryCreate: ProfileSummaryCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileSummary>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateProfileSummaryApiV1MemorySummariesGeneratePost(profileSummaryCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.generateProfileSummaryApiV1MemorySummariesGeneratePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get complete memory context for a user.
         * @summary Get Memory Context
         * @param {number} userId 
         * @param {string | null} [query] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMemoryContextApiV1MemoryContextUserIdGet(userId: number, query?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MemoryContext>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMemoryContextApiV1MemoryContextUserIdGet(userId, query, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.getMemoryContextApiV1MemoryContextUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get memory statistics for a user.
         * @summary Get Memory Stats
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMemoryStatsApiV1MemoryStatsUserIdGet(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MemoryStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMemoryStatsApiV1MemoryStatsUserIdGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.getMemoryStatsApiV1MemoryStatsUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all profile summaries for a user.
         * @summary Get Profile Summaries
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProfileSummariesApiV1MemorySummariesUserIdGet(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProfileSummary>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProfileSummariesApiV1MemorySummariesUserIdGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.getProfileSummariesApiV1MemorySummariesUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all facts for a user.
         * @summary Get User Facts
         * @param {number} userId 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string | null} [category] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserFactsApiV1MemoryFactsUserIdGet(userId: number, limit?: number, offset?: number, category?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserFact>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserFactsApiV1MemoryFactsUserIdGet(userId, limit, offset, category, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.getUserFactsApiV1MemoryFactsUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Search for relevant facts using semantic similarity.
         * @summary Search Facts
         * @param {FactSearch} factSearch 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchFactsApiV1MemoryFactsSearchPost(factSearch: FactSearch, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FactSearchResult>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchFactsApiV1MemoryFactsSearchPost(factSearch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MemoryApi.searchFactsApiV1MemoryFactsSearchPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MemoryApi - factory interface
 * @export
 */
export const MemoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MemoryApiFp(configuration)
    return {
        /**
         * Store a new fact for a user.
         * @summary Create Fact
         * @param {MemoryApiCreateFactApiV1MemoryFactsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFactApiV1MemoryFactsPost(requestParameters: MemoryApiCreateFactApiV1MemoryFactsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserFact> {
            return localVarFp.createFactApiV1MemoryFactsPost(requestParameters.factCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a specific fact.
         * @summary Delete Fact
         * @param {MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFactApiV1MemoryFactsFactIdDelete(requestParameters: MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.deleteFactApiV1MemoryFactsFactIdDelete(requestParameters.factId, options).then((request) => request(axios, basePath));
        },
        /**
         * Generate or update user profile summary.
         * @summary Generate Profile Summary
         * @param {MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateProfileSummaryApiV1MemorySummariesGeneratePost(requestParameters: MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProfileSummary> {
            return localVarFp.generateProfileSummaryApiV1MemorySummariesGeneratePost(requestParameters.profileSummaryCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Get complete memory context for a user.
         * @summary Get Memory Context
         * @param {MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemoryContextApiV1MemoryContextUserIdGet(requestParameters: MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MemoryContext> {
            return localVarFp.getMemoryContextApiV1MemoryContextUserIdGet(requestParameters.userId, requestParameters.query, options).then((request) => request(axios, basePath));
        },
        /**
         * Get memory statistics for a user.
         * @summary Get Memory Stats
         * @param {MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemoryStatsApiV1MemoryStatsUserIdGet(requestParameters: MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MemoryStats> {
            return localVarFp.getMemoryStatsApiV1MemoryStatsUserIdGet(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all profile summaries for a user.
         * @summary Get Profile Summaries
         * @param {MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProfileSummariesApiV1MemorySummariesUserIdGet(requestParameters: MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProfileSummary>> {
            return localVarFp.getProfileSummariesApiV1MemorySummariesUserIdGet(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all facts for a user.
         * @summary Get User Facts
         * @param {MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserFactsApiV1MemoryFactsUserIdGet(requestParameters: MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserFact>> {
            return localVarFp.getUserFactsApiV1MemoryFactsUserIdGet(requestParameters.userId, requestParameters.limit, requestParameters.offset, requestParameters.category, options).then((request) => request(axios, basePath));
        },
        /**
         * Search for relevant facts using semantic similarity.
         * @summary Search Facts
         * @param {MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchFactsApiV1MemoryFactsSearchPost(requestParameters: MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<FactSearchResult>> {
            return localVarFp.searchFactsApiV1MemoryFactsSearchPost(requestParameters.factSearch, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MemoryApi - interface
 * @export
 * @interface MemoryApi
 */
export interface MemoryApiInterface {
    /**
     * Store a new fact for a user.
     * @summary Create Fact
     * @param {MemoryApiCreateFactApiV1MemoryFactsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    createFactApiV1MemoryFactsPost(requestParameters: MemoryApiCreateFactApiV1MemoryFactsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserFact>;

    /**
     * Delete a specific fact.
     * @summary Delete Fact
     * @param {MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    deleteFactApiV1MemoryFactsFactIdDelete(requestParameters: MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }>;

    /**
     * Generate or update user profile summary.
     * @summary Generate Profile Summary
     * @param {MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    generateProfileSummaryApiV1MemorySummariesGeneratePost(requestParameters: MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProfileSummary>;

    /**
     * Get complete memory context for a user.
     * @summary Get Memory Context
     * @param {MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    getMemoryContextApiV1MemoryContextUserIdGet(requestParameters: MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MemoryContext>;

    /**
     * Get memory statistics for a user.
     * @summary Get Memory Stats
     * @param {MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    getMemoryStatsApiV1MemoryStatsUserIdGet(requestParameters: MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<MemoryStats>;

    /**
     * Get all profile summaries for a user.
     * @summary Get Profile Summaries
     * @param {MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    getProfileSummariesApiV1MemorySummariesUserIdGet(requestParameters: MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProfileSummary>>;

    /**
     * Get all facts for a user.
     * @summary Get User Facts
     * @param {MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    getUserFactsApiV1MemoryFactsUserIdGet(requestParameters: MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserFact>>;

    /**
     * Search for relevant facts using semantic similarity.
     * @summary Search Facts
     * @param {MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    searchFactsApiV1MemoryFactsSearchPost(requestParameters: MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<FactSearchResult>>;

}

/**
 * Request parameters for createFactApiV1MemoryFactsPost operation in MemoryApi.
 * @export
 * @interface MemoryApiCreateFactApiV1MemoryFactsPostRequest
 */
export interface MemoryApiCreateFactApiV1MemoryFactsPostRequest {
    /**
     * 
     * @type {FactCreate}
     * @memberof MemoryApiCreateFactApiV1MemoryFactsPost
     */
    readonly factCreate: FactCreate
}

/**
 * Request parameters for deleteFactApiV1MemoryFactsFactIdDelete operation in MemoryApi.
 * @export
 * @interface MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest
 */
export interface MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest {
    /**
     * 
     * @type {number}
     * @memberof MemoryApiDeleteFactApiV1MemoryFactsFactIdDelete
     */
    readonly factId: number
}

/**
 * Request parameters for generateProfileSummaryApiV1MemorySummariesGeneratePost operation in MemoryApi.
 * @export
 * @interface MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest
 */
export interface MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest {
    /**
     * 
     * @type {ProfileSummaryCreate}
     * @memberof MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePost
     */
    readonly profileSummaryCreate: ProfileSummaryCreate
}

/**
 * Request parameters for getMemoryContextApiV1MemoryContextUserIdGet operation in MemoryApi.
 * @export
 * @interface MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest
 */
export interface MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof MemoryApiGetMemoryContextApiV1MemoryContextUserIdGet
     */
    readonly userId: number

    /**
     * 
     * @type {string}
     * @memberof MemoryApiGetMemoryContextApiV1MemoryContextUserIdGet
     */
    readonly query?: string | null
}

/**
 * Request parameters for getMemoryStatsApiV1MemoryStatsUserIdGet operation in MemoryApi.
 * @export
 * @interface MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest
 */
export interface MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGet
     */
    readonly userId: number
}

/**
 * Request parameters for getProfileSummariesApiV1MemorySummariesUserIdGet operation in MemoryApi.
 * @export
 * @interface MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest
 */
export interface MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGet
     */
    readonly userId: number
}

/**
 * Request parameters for getUserFactsApiV1MemoryFactsUserIdGet operation in MemoryApi.
 * @export
 * @interface MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest
 */
export interface MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof MemoryApiGetUserFactsApiV1MemoryFactsUserIdGet
     */
    readonly userId: number

    /**
     * 
     * @type {number}
     * @memberof MemoryApiGetUserFactsApiV1MemoryFactsUserIdGet
     */
    readonly limit?: number

    /**
     * 
     * @type {number}
     * @memberof MemoryApiGetUserFactsApiV1MemoryFactsUserIdGet
     */
    readonly offset?: number

    /**
     * 
     * @type {string}
     * @memberof MemoryApiGetUserFactsApiV1MemoryFactsUserIdGet
     */
    readonly category?: string | null
}

/**
 * Request parameters for searchFactsApiV1MemoryFactsSearchPost operation in MemoryApi.
 * @export
 * @interface MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest
 */
export interface MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest {
    /**
     * 
     * @type {FactSearch}
     * @memberof MemoryApiSearchFactsApiV1MemoryFactsSearchPost
     */
    readonly factSearch: FactSearch
}

/**
 * MemoryApi - object-oriented interface
 * @export
 * @class MemoryApi
 * @extends {BaseAPI}
 */
export class MemoryApi extends BaseAPI implements MemoryApiInterface {
    /**
     * Store a new fact for a user.
     * @summary Create Fact
     * @param {MemoryApiCreateFactApiV1MemoryFactsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public createFactApiV1MemoryFactsPost(requestParameters: MemoryApiCreateFactApiV1MemoryFactsPostRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).createFactApiV1MemoryFactsPost(requestParameters.factCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a specific fact.
     * @summary Delete Fact
     * @param {MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public deleteFactApiV1MemoryFactsFactIdDelete(requestParameters: MemoryApiDeleteFactApiV1MemoryFactsFactIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).deleteFactApiV1MemoryFactsFactIdDelete(requestParameters.factId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Generate or update user profile summary.
     * @summary Generate Profile Summary
     * @param {MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public generateProfileSummaryApiV1MemorySummariesGeneratePost(requestParameters: MemoryApiGenerateProfileSummaryApiV1MemorySummariesGeneratePostRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).generateProfileSummaryApiV1MemorySummariesGeneratePost(requestParameters.profileSummaryCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get complete memory context for a user.
     * @summary Get Memory Context
     * @param {MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public getMemoryContextApiV1MemoryContextUserIdGet(requestParameters: MemoryApiGetMemoryContextApiV1MemoryContextUserIdGetRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).getMemoryContextApiV1MemoryContextUserIdGet(requestParameters.userId, requestParameters.query, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get memory statistics for a user.
     * @summary Get Memory Stats
     * @param {MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public getMemoryStatsApiV1MemoryStatsUserIdGet(requestParameters: MemoryApiGetMemoryStatsApiV1MemoryStatsUserIdGetRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).getMemoryStatsApiV1MemoryStatsUserIdGet(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all profile summaries for a user.
     * @summary Get Profile Summaries
     * @param {MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public getProfileSummariesApiV1MemorySummariesUserIdGet(requestParameters: MemoryApiGetProfileSummariesApiV1MemorySummariesUserIdGetRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).getProfileSummariesApiV1MemorySummariesUserIdGet(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all facts for a user.
     * @summary Get User Facts
     * @param {MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public getUserFactsApiV1MemoryFactsUserIdGet(requestParameters: MemoryApiGetUserFactsApiV1MemoryFactsUserIdGetRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).getUserFactsApiV1MemoryFactsUserIdGet(requestParameters.userId, requestParameters.limit, requestParameters.offset, requestParameters.category, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Search for relevant facts using semantic similarity.
     * @summary Search Facts
     * @param {MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApi
     */
    public searchFactsApiV1MemoryFactsSearchPost(requestParameters: MemoryApiSearchFactsApiV1MemoryFactsSearchPostRequest, options?: RawAxiosRequestConfig) {
        return MemoryApiFp(this.configuration).searchFactsApiV1MemoryFactsSearchPost(requestParameters.factSearch, options).then((request) => request(this.axios, this.basePath));
    }
}

