/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { SynthesisRequest } from '../models';
// @ts-ignore
import type { SynthesisResponse } from '../models';
// @ts-ignore
import type { TTSProvider } from '../models';
// @ts-ignore
import type { TranscriptionResponse } from '../models';
// @ts-ignore
import type { VoiceProcessingResponse } from '../models';
/**
 * VoiceApi - axios parameter creator
 * @export
 */
export const VoiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Download a generated audio file.
         * @summary Get Audio File
         * @param {string} audioId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAudioFileApiV1VoiceAudioAudioIdGet: async (audioId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'audioId' is not null or undefined
            assertParamExists('getAudioFileApiV1VoiceAudioAudioIdGet', 'audioId', audioId)
            const localVarPath = `/api/v1/voice/audio/{audio_id}`
                .replace(`{${"audio_id"}}`, encodeURIComponent(String(audioId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get available TTS providers and their capabilities.
         * @summary Get Tts Providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTtsProvidersApiV1VoiceProvidersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/voice/providers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Complete voice processing pipeline: STT -> AI -> TTS.
         * @summary Process Voice Message
         * @param {File} audioFile 
         * @param {number} userId 
         * @param {string | null} [language] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processVoiceMessageApiV1VoiceProcessPost: async (audioFile: File, userId: number, language?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'audioFile' is not null or undefined
            assertParamExists('processVoiceMessageApiV1VoiceProcessPost', 'audioFile', audioFile)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('processVoiceMessageApiV1VoiceProcessPost', 'userId', userId)
            const localVarPath = `/api/v1/voice/process`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (audioFile !== undefined) { 
                localVarFormParams.append('audio_file', audioFile as any);
            }
    
            if (userId !== undefined) { 
                localVarFormParams.append('user_id', userId as any);
            }
    
            if (language !== undefined) { 
                localVarFormParams.append('language', language as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Synthesize text to speech using TTS.
         * @summary Synthesize Speech
         * @param {SynthesisRequest} synthesisRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        synthesizeSpeechApiV1VoiceSynthesizePost: async (synthesisRequest: SynthesisRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'synthesisRequest' is not null or undefined
            assertParamExists('synthesizeSpeechApiV1VoiceSynthesizePost', 'synthesisRequest', synthesisRequest)
            const localVarPath = `/api/v1/voice/synthesize`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(synthesisRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Transcribe audio to text using STT.
         * @summary Transcribe Audio
         * @param {File} audioFile 
         * @param {number | null} [userId] 
         * @param {string | null} [language] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transcribeAudioApiV1VoiceTranscribePost: async (audioFile: File, userId?: number | null, language?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'audioFile' is not null or undefined
            assertParamExists('transcribeAudioApiV1VoiceTranscribePost', 'audioFile', audioFile)
            const localVarPath = `/api/v1/voice/transcribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (audioFile !== undefined) { 
                localVarFormParams.append('audio_file', audioFile as any);
            }
    
            if (userId !== undefined) { 
                localVarFormParams.append('user_id', userId as any);
            }
    
            if (language !== undefined) { 
                localVarFormParams.append('language', language as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VoiceApi - functional programming interface
 * @export
 */
export const VoiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VoiceApiAxiosParamCreator(configuration)
    return {
        /**
         * Download a generated audio file.
         * @summary Get Audio File
         * @param {string} audioId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAudioFileApiV1VoiceAudioAudioIdGet(audioId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAudioFileApiV1VoiceAudioAudioIdGet(audioId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoiceApi.getAudioFileApiV1VoiceAudioAudioIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get available TTS providers and their capabilities.
         * @summary Get Tts Providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTtsProvidersApiV1VoiceProvidersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TTSProvider>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTtsProvidersApiV1VoiceProvidersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoiceApi.getTtsProvidersApiV1VoiceProvidersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Complete voice processing pipeline: STT -> AI -> TTS.
         * @summary Process Voice Message
         * @param {File} audioFile 
         * @param {number} userId 
         * @param {string | null} [language] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processVoiceMessageApiV1VoiceProcessPost(audioFile: File, userId: number, language?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VoiceProcessingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.processVoiceMessageApiV1VoiceProcessPost(audioFile, userId, language, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoiceApi.processVoiceMessageApiV1VoiceProcessPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Synthesize text to speech using TTS.
         * @summary Synthesize Speech
         * @param {SynthesisRequest} synthesisRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async synthesizeSpeechApiV1VoiceSynthesizePost(synthesisRequest: SynthesisRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SynthesisResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.synthesizeSpeechApiV1VoiceSynthesizePost(synthesisRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoiceApi.synthesizeSpeechApiV1VoiceSynthesizePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Transcribe audio to text using STT.
         * @summary Transcribe Audio
         * @param {File} audioFile 
         * @param {number | null} [userId] 
         * @param {string | null} [language] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async transcribeAudioApiV1VoiceTranscribePost(audioFile: File, userId?: number | null, language?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TranscriptionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.transcribeAudioApiV1VoiceTranscribePost(audioFile, userId, language, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VoiceApi.transcribeAudioApiV1VoiceTranscribePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VoiceApi - factory interface
 * @export
 */
export const VoiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VoiceApiFp(configuration)
    return {
        /**
         * Download a generated audio file.
         * @summary Get Audio File
         * @param {VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAudioFileApiV1VoiceAudioAudioIdGet(requestParameters: VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getAudioFileApiV1VoiceAudioAudioIdGet(requestParameters.audioId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get available TTS providers and their capabilities.
         * @summary Get Tts Providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTtsProvidersApiV1VoiceProvidersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<TTSProvider>> {
            return localVarFp.getTtsProvidersApiV1VoiceProvidersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Complete voice processing pipeline: STT -> AI -> TTS.
         * @summary Process Voice Message
         * @param {VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processVoiceMessageApiV1VoiceProcessPost(requestParameters: VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<VoiceProcessingResponse> {
            return localVarFp.processVoiceMessageApiV1VoiceProcessPost(requestParameters.audioFile, requestParameters.userId, requestParameters.language, options).then((request) => request(axios, basePath));
        },
        /**
         * Synthesize text to speech using TTS.
         * @summary Synthesize Speech
         * @param {VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        synthesizeSpeechApiV1VoiceSynthesizePost(requestParameters: VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SynthesisResponse> {
            return localVarFp.synthesizeSpeechApiV1VoiceSynthesizePost(requestParameters.synthesisRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Transcribe audio to text using STT.
         * @summary Transcribe Audio
         * @param {VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        transcribeAudioApiV1VoiceTranscribePost(requestParameters: VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TranscriptionResponse> {
            return localVarFp.transcribeAudioApiV1VoiceTranscribePost(requestParameters.audioFile, requestParameters.userId, requestParameters.language, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VoiceApi - interface
 * @export
 * @interface VoiceApi
 */
export interface VoiceApiInterface {
    /**
     * Download a generated audio file.
     * @summary Get Audio File
     * @param {VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApiInterface
     */
    getAudioFileApiV1VoiceAudioAudioIdGet(requestParameters: VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * Get available TTS providers and their capabilities.
     * @summary Get Tts Providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApiInterface
     */
    getTtsProvidersApiV1VoiceProvidersGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<TTSProvider>>;

    /**
     * Complete voice processing pipeline: STT -> AI -> TTS.
     * @summary Process Voice Message
     * @param {VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApiInterface
     */
    processVoiceMessageApiV1VoiceProcessPost(requestParameters: VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<VoiceProcessingResponse>;

    /**
     * Synthesize text to speech using TTS.
     * @summary Synthesize Speech
     * @param {VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApiInterface
     */
    synthesizeSpeechApiV1VoiceSynthesizePost(requestParameters: VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SynthesisResponse>;

    /**
     * Transcribe audio to text using STT.
     * @summary Transcribe Audio
     * @param {VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApiInterface
     */
    transcribeAudioApiV1VoiceTranscribePost(requestParameters: VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TranscriptionResponse>;

}

/**
 * Request parameters for getAudioFileApiV1VoiceAudioAudioIdGet operation in VoiceApi.
 * @export
 * @interface VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest
 */
export interface VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest {
    /**
     * 
     * @type {string}
     * @memberof VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGet
     */
    readonly audioId: string
}

/**
 * Request parameters for processVoiceMessageApiV1VoiceProcessPost operation in VoiceApi.
 * @export
 * @interface VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest
 */
export interface VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest {
    /**
     * 
     * @type {File}
     * @memberof VoiceApiProcessVoiceMessageApiV1VoiceProcessPost
     */
    readonly audioFile: File

    /**
     * 
     * @type {number}
     * @memberof VoiceApiProcessVoiceMessageApiV1VoiceProcessPost
     */
    readonly userId: number

    /**
     * 
     * @type {string}
     * @memberof VoiceApiProcessVoiceMessageApiV1VoiceProcessPost
     */
    readonly language?: string | null
}

/**
 * Request parameters for synthesizeSpeechApiV1VoiceSynthesizePost operation in VoiceApi.
 * @export
 * @interface VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest
 */
export interface VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest {
    /**
     * 
     * @type {SynthesisRequest}
     * @memberof VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePost
     */
    readonly synthesisRequest: SynthesisRequest
}

/**
 * Request parameters for transcribeAudioApiV1VoiceTranscribePost operation in VoiceApi.
 * @export
 * @interface VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest
 */
export interface VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest {
    /**
     * 
     * @type {File}
     * @memberof VoiceApiTranscribeAudioApiV1VoiceTranscribePost
     */
    readonly audioFile: File

    /**
     * 
     * @type {number}
     * @memberof VoiceApiTranscribeAudioApiV1VoiceTranscribePost
     */
    readonly userId?: number | null

    /**
     * 
     * @type {string}
     * @memberof VoiceApiTranscribeAudioApiV1VoiceTranscribePost
     */
    readonly language?: string | null
}

/**
 * VoiceApi - object-oriented interface
 * @export
 * @class VoiceApi
 * @extends {BaseAPI}
 */
export class VoiceApi extends BaseAPI implements VoiceApiInterface {
    /**
     * Download a generated audio file.
     * @summary Get Audio File
     * @param {VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApi
     */
    public getAudioFileApiV1VoiceAudioAudioIdGet(requestParameters: VoiceApiGetAudioFileApiV1VoiceAudioAudioIdGetRequest, options?: RawAxiosRequestConfig) {
        return VoiceApiFp(this.configuration).getAudioFileApiV1VoiceAudioAudioIdGet(requestParameters.audioId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get available TTS providers and their capabilities.
     * @summary Get Tts Providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApi
     */
    public getTtsProvidersApiV1VoiceProvidersGet(options?: RawAxiosRequestConfig) {
        return VoiceApiFp(this.configuration).getTtsProvidersApiV1VoiceProvidersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Complete voice processing pipeline: STT -> AI -> TTS.
     * @summary Process Voice Message
     * @param {VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApi
     */
    public processVoiceMessageApiV1VoiceProcessPost(requestParameters: VoiceApiProcessVoiceMessageApiV1VoiceProcessPostRequest, options?: RawAxiosRequestConfig) {
        return VoiceApiFp(this.configuration).processVoiceMessageApiV1VoiceProcessPost(requestParameters.audioFile, requestParameters.userId, requestParameters.language, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Synthesize text to speech using TTS.
     * @summary Synthesize Speech
     * @param {VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApi
     */
    public synthesizeSpeechApiV1VoiceSynthesizePost(requestParameters: VoiceApiSynthesizeSpeechApiV1VoiceSynthesizePostRequest, options?: RawAxiosRequestConfig) {
        return VoiceApiFp(this.configuration).synthesizeSpeechApiV1VoiceSynthesizePost(requestParameters.synthesisRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Transcribe audio to text using STT.
     * @summary Transcribe Audio
     * @param {VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoiceApi
     */
    public transcribeAudioApiV1VoiceTranscribePost(requestParameters: VoiceApiTranscribeAudioApiV1VoiceTranscribePostRequest, options?: RawAxiosRequestConfig) {
        return VoiceApiFp(this.configuration).transcribeAudioApiV1VoiceTranscribePost(requestParameters.audioFile, requestParameters.userId, requestParameters.language, options).then((request) => request(this.axios, this.basePath));
    }
}

