#!/usr/bin/env python3
"""
Database Population Script for Learn Words Application

This script populates the database with translations for all language pairs using
the existing translation system. It processes word lists generated by the word list
generator and creates comprehensive translation data for all supported language combinations.

Usage:
    python scripts/populate_database.py --all-pairs
    python scripts/populate_database.py --pairs english-polish,polish-english
    python scripts/populate_database.py --resume
    python scripts/populate_database.py --help
"""

import asyncio
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple, Optional
import signal
import click

from scripts.util import (
    TokenBucketRateLimiter,
    CircuitBreaker,
    PerformanceMonitor,
    ParallelProgressTracker,
    ErrorClassifier,
    setup_logging,
)

# Add the project root to the Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

# Import application modules
from src.database import Database, db
from src.translation.translator import TranslationService

logger = logging.getLogger(__name__)


class DatabasePopulator:
    """Populates the database with word translations for all language pairs."""

    def __init__(self):
        self.script_dir = Path(__file__).parent
        self.generated_lists_dir = self.script_dir / "generated_lists"
        self.checkpoints_dir = self.script_dir / "checkpoints"
        self.reports_dir = self.script_dir / "reports"

        # Ensure directories exist
        self.checkpoints_dir.mkdir(exist_ok=True)
        self.reports_dir.mkdir(exist_ok=True)

        # Setup logging with correct paths
        setup_logging(self.script_dir)

        # Database and translator instances
        self.db: Optional[Database] = None
        # Word source configuration
        self.word_source = "files"  # files, database, mixed
        self.db_languages = []  # languages to fetch from DB
        self.translator: Optional[TranslationService] = None

        # Supported languages
        self.supported_languages = ["english", "polish", "russian", "spanish"]

        # All possible language pairs (bidirectional)
        self.all_language_pairs = [
            # ("english", "polish"),
            # ("polish", "english"),
            # ("english", "russian"),
            ("russian", "english"),
            # ("english", "spanish"),
            # ("spanish", "english"),
            # ("polish", "russian"),
            ("russian", "polish"),
            # ("polish", "spanish"),
            # ("spanish", "polish"),
            ("russian", "spanish"),
            # ("spanish", "russian"),
        ]

        # Configuration
        self.batch_size = 50
        self.rate_limit_delay = 0.1  # seconds between API calls
        self.max_retries = 3
        self.checkpoint_interval = 100

        # Parallel processing configuration
        self.max_concurrent = 25
        self.requests_per_second = 50.0
        self.adaptive_rate = True
        self.circuit_breaker_enabled = True
        self.batch_db_writes = True
        self.performance_monitoring = True

        # Progress tracking
        self.total_words_processed = 0
        self.total_words_skipped = 0
        self.total_errors = 0
        self.start_time = None

        # Parallel processing components
        self.rate_limiter = None
        self.circuit_breaker = None
        self.progress_tracker = None
        self.performance_monitor = None

        # Graceful shutdown handling
        self.shutdown_requested = False
        signal.signal(signal.SIGINT, self._signal_handler)
        signal.signal(signal.SIGTERM, self._signal_handler)

    def _signal_handler(self, signum, frame):
        """Handle shutdown signals gracefully."""
        logger.info("Shutdown signal received. Finishing current batch and saving checkpoint...")
        self.shutdown_requested = True

    async def initialize(self):
        """Initialize database and translator connections."""
        logger.info("Initializing database and translator...")

        try:
            # Initialize database
            self.db = Database()
            await self.db.connect()
            await db.connect()

            logger.info("Database connection established")

            # Initialize translator
            self.translator = TranslationService()
            logger.info("Translator initialized")

        except Exception as e:
            logger.error(f"Failed to initialize: {e}")
            raise

    async def cleanup(self):
        """Clean up database connections."""
        if self.db:
            await self.db.close()
            logger.info("Database connection closed")

    async def load_word_lists(self) -> Dict[str, List[Dict]]:
        """Load word lists based on configured source (files, database, or mixed)."""
        if self.word_source == "database":
            return await self.load_word_lists_from_database(self.db_languages or self.supported_languages)
        elif self.word_source == "mixed":
            return await self.load_word_lists_mixed(self.db_languages or [])
        else:  # files
            return self.load_word_lists_from_files()

    async def load_word_lists_from_database(self, languages: List[str]) -> Dict[str, List[Dict]]:
        """Load word lists from database for specified languages."""
        if not self.db:
            logger.error("Database not initialized")
            return {}

        try:
            word_lists = await self.db.get_words_by_languages(languages)

            # Log statistics
            for language, words in word_lists.items():
                logger.info(f"Loaded {len(words)} words for {language} from database")

            return word_lists

        except Exception as e:
            logger.error(f"Failed to load words from database: {e}")
            return {}

    async def load_word_lists_mixed(self, db_languages: List[str]) -> Dict[str, List[Dict]]:
        """Load word lists from both database and files."""
        word_lists = {}

        # Load from database for specified languages
        if db_languages:
            db_word_lists = await self.load_word_lists_from_database(db_languages)
            word_lists.update(db_word_lists)

        # Load from files for remaining languages
        file_languages = [lang for lang in self.supported_languages if lang not in db_languages]
        if file_languages:
            file_word_lists = self.load_word_lists_from_files(file_languages)
            word_lists.update(file_word_lists)

        return word_lists

    def load_word_lists_from_files(self, languages: List[str] = None) -> Dict[str, List[Dict]]:
        """Load word lists from JSON files for specified languages."""
        if languages is None:
            languages = self.supported_languages

        word_lists = {}

        for language in languages:
            # Look for word list files (try different counts)
            possible_files = [
                f"{language}_9700.json",
                f"{language}_5000.json",
                f"{language}_3000.json",
                f"{language}_1000.json",
                f"{language}_100.json",
                f"{language}.json",
            ]

            word_list_file = None
            for filename in possible_files:
                filepath = self.generated_lists_dir / filename
                if filepath.exists():
                    word_list_file = filepath
                    break

            if word_list_file:
                try:
                    with open(word_list_file, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        word_lists[language] = data["words"]
                        logger.info(f"Loaded {len(data['words'])} words for {language} from {word_list_file.name}")
                except Exception as e:
                    logger.error(f"Failed to load word list for {language}: {e}")
            else:
                logger.warning(f"No word list found for {language}")

        return word_lists

    async def show_database_statistics(self):
        """Show comprehensive database word statistics."""
        if not self.db:
            logger.error("Database not initialized")
            return

        try:
            stats = await self.db.get_database_word_statistics()

            print("\n" + "=" * 60)
            print("DATABASE WORD STATISTICS")
            print("=" * 60)

            print(f"\nTotal Statistics:")
            print(f"  Unique words: {stats['total_unique_words']:,}")
            print(f"  Total translations: {stats['total_translations']:,}")
            print(f"  Languages: {stats['total_languages']}")

            if stats["first_word_added"]:
                print(f"  First word added: {stats['first_word_added']}")
            if stats["last_word_added"]:
                print(f"  Last word added: {stats['last_word_added']}")

            print(f"\nWord Counts by Language:")
            for language, count in stats["word_counts_by_language"].items():
                print(f"  {language}: {count:,} words")

            print(f"\nLanguage Pairs:")
            for pair in stats["language_pairs"]:
                print(
                    f"  {pair['from_language']} → {pair['to_language']}: " f"{pair['word_count']:,} words, {pair['translation_count']:,} translations"
                )

            print("=" * 60)

        except Exception as e:
            logger.error(f"Failed to get database statistics: {e}")

    def get_language_pairs(self, pairs_arg: Optional[str] = None) -> List[Tuple[str, str]]:
        """Get the list of language pairs to process."""
        if pairs_arg:
            # Parse specific pairs from argument
            pairs = []
            for pair_str in pairs_arg.split(","):
                pair_str = pair_str.strip()
                if "-" in pair_str:
                    from_lang, to_lang = pair_str.split("-", 1)
                    pairs.append((from_lang.strip(), to_lang.strip()))
                else:
                    logger.warning(f"Invalid pair format: {pair_str}")
            return pairs
        else:
            # Return all possible pairs
            return self.all_language_pairs

    def load_checkpoint(self, checkpoint_name: str) -> Optional[Dict]:
        """Load checkpoint data for resuming."""
        checkpoint_file = self.checkpoints_dir / f"{checkpoint_name}.json"

        if checkpoint_file.exists():
            try:
                with open(checkpoint_file, "r", encoding="utf-8") as f:
                    checkpoint_data = json.load(f)
                    logger.info(f"Loaded checkpoint: {checkpoint_file}")
                    return checkpoint_data
            except Exception as e:
                logger.error(f"Failed to load checkpoint {checkpoint_file}: {e}")

        return None

    def save_checkpoint(self, checkpoint_name: str, data: Dict):
        """Save checkpoint data for resuming."""
        checkpoint_file = self.checkpoints_dir / f"{checkpoint_name}.json"

        try:
            with open(checkpoint_file, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, default=str)
                logger.info(f"Checkpoint saved: {checkpoint_file}")
        except Exception as e:
            logger.error(f"Failed to save checkpoint {checkpoint_file}: {e}")

    async def check_word_exists(
        self,
        word: str,
        from_lang: str,
        to_lang: str,
        native_language: Optional[str] = None,
    ) -> bool:
        """Check if a word translation already exists in the database."""
        try:
            # If native_language is not provided, use to_lang as default
            if native_language is None:
                native_language = to_lang

            existing_word = await self.db.get_word(
                word.lower().strip(),
                from_lang.lower(),
                to_lang.lower(),
                native_language.lower(),
            )
            return existing_word is not None
        except Exception as e:
            logger.warning(f"Error checking word existence: {e}")
            return False

    async def translate_and_save_word(
        self,
        word: str,
        from_lang: str,
        to_lang: str,
        user_native: str,
        user_learning: str,
        native_language: Optional[str] = None,
    ) -> bool:
        """Translate a word and save it to the database."""
        try:
            # Skip normalization and go straight to LLM as requested
            logger.debug(f"Translating '{word}' ({from_lang} -> {to_lang})")

            # Use the enhanced translation method
            # If native_language is not provided, use user_learning as default
            if native_language is None:
                native_language = user_native

            translation_data = await self.translator.translate_word_enhanced(
                word=word,
                from_language=from_lang,
                to_language=to_lang,
                user_native=user_native,
                user_learning=user_learning,
            )

            if translation_data:
                return True
            else:
                return False

        except Exception as e:
            logger.error(f"Error translating '{word}' ({from_lang} -> {to_lang}): {e}")
            return False

    async def _translate_with_retry(
        self,
        word: str,
        from_lang: str,
        to_lang: str,
        user_native: str,
        user_learning: str,
        max_retries: int = 3,
    ) -> bool:
        if from_lang == user_learning:
            return False
        """Translate a word with retry logic and exponential backoff."""
        for attempt in range(max_retries):
            try:
                success = await self.translate_and_save_word(word, from_lang, to_lang, user_native, user_learning, user_learning)
                return success
            except Exception as e:
                error_type = ErrorClassifier.classify_error(e)

                if error_type == "RATE_LIMIT":
                    # Exponential backoff for rate limits
                    wait_time = (2**attempt) + (0.1 * attempt)
                    logger.warning(f"Rate limit hit for '{word}', waiting {wait_time:.1f}s (attempt {attempt + 1})")
                    await asyncio.sleep(wait_time)
                elif attempt == max_retries - 1:
                    # Last attempt failed
                    logger.error(f"Failed to translate '{word}' after {max_retries} attempts: {e}")
                    return False
                else:
                    # Other errors - shorter wait
                    wait_time = 0.5 * (attempt + 1)
                    logger.warning(f"Translation error for '{word}', retrying in {wait_time:.1f}s: {e}")
                    await asyncio.sleep(wait_time)

        return False

    def _determine_native_language(self, from_lang: str, to_lang: str) -> str:
        """Determine the native language for a language pair.

        For language learning, we typically want one consistent native language.
        For example, for both 'russian-english' and 'english-russian' pairs,
        if the user is learning English, Russian should be the native language.
        """
        # Priority order for native languages (customize based on your use case)
        native_priority = ["russian", "polish", "spanish", "english"]

        # Check if either language is in our priority list
        for native_lang in native_priority:
            if native_lang in [from_lang, to_lang]:
                return native_lang

        # Fallback: use the first language alphabetically
        return min(from_lang, to_lang)

    async def process_batch_parallel_bidirectional(self, batch_plan: List[Dict], native_language: str, batch_index: int) -> Dict:
        """Process a batch of bidirectional translations with parallel processing."""

        batch_start_time = time.time()

        # Initialize parallel processing components
        semaphore = asyncio.Semaphore(self.max_concurrent)
        rate_limiter = TokenBucketRateLimiter(
            rate=self.requests_per_second,
            burst=self.max_concurrent,
            adaptive=self.adaptive_rate,
        )
        circuit_breaker = CircuitBreaker() if self.circuit_breaker_enabled else None

        # Statistics tracking
        stats = {
            "processed": 0,
            "skipped": 0,
            "errors": 0,
            "error_rate_limit": 0,
            "error_api_error": 0,
            "error_timeout": 0,
            "error_network": 0,
            "error_parse_error": 0,
            "error_unknown": 0,
        }

        # Create parallel translation tasks for bidirectional processing
        tasks = []
        for plan_item in batch_plan:
            task = asyncio.create_task(
                self.translate_word_parallel_bidirectional(
                    plan_item,
                    native_language,
                    semaphore,
                    rate_limiter,
                    circuit_breaker or CircuitBreaker(),
                    stats,
                )
            )
            tasks.append(task)

        # Execute all tasks concurrently with progress tracking
        results = []
        completed = 0

        # Process tasks as they complete
        for coro in asyncio.as_completed(tasks):
            try:
                result = await coro
                results.append(result)
                completed += 1

                # Log progress every 10 completions
                if completed % 10 == 0:
                    progress = completed / len(tasks) * 100
                    logger.info(f"Batch {batch_index}: {progress:.1f}% complete ({completed}/{len(tasks)})")

            except Exception as e:
                logger.error(f"Task failed in batch {batch_index}: {e}")
                results.append((False, "task_failed"))
                stats["errors"] += 1

        # Calculate batch statistics
        batch_duration = time.time() - batch_start_time
        throughput = len(batch_plan) / batch_duration if batch_duration > 0 else 0

        batch_stats = {
            "batch_index": batch_index,
            "total_words": len(batch_plan),
            "duration": batch_duration,
            "throughput": throughput,
            "concurrent_tasks": self.max_concurrent,
            **stats,
        }

        logger.info(
            f"Batch {batch_index} completed: {stats['processed']} processed, "
            f"{stats['skipped']} skipped, {stats['errors']} errors "
            f"in {batch_duration:.1f}s ({throughput:.1f} words/s)"
        )

        return batch_stats

    async def translate_word_parallel_bidirectional(
        self,
        plan_item: Dict,
        native_language: str,
        semaphore: asyncio.Semaphore,
        rate_limiter: TokenBucketRateLimiter,
        circuit_breaker: CircuitBreaker,
        stats: Dict,
    ) -> Tuple[bool, Optional[str]]:
        """Translate a single word with bidirectional parallel processing support."""

        async with semaphore:  # Limit concurrency
            word_entry = plan_item["word_entry"]
            word = word_entry["word"]
            source_lang = plan_item["source_lang"]
            target_lang = plan_item["target_lang"]
            direction = plan_item["direction"]

            try:
                # Check circuit breaker
                if await circuit_breaker.is_open():
                    stats["errors"] += 1
                    return False, "circuit_breaker_open"

                # Rate limiting
                await rate_limiter.acquire()

                # Record performance metrics
                if self.performance_monitor:
                    await self.performance_monitor.record_cache_miss()

                # Check cache first
                if await self.check_word_exists(word, source_lang, target_lang, native_language):
                    stats["skipped"] += 1
                    if self.performance_monitor:
                        await self.performance_monitor.record_cache_hit()
                    logger.debug(f"Word '{word}' ({direction}) already exists, skipping")
                    return True, "skipped"

                # Translate with retry logic
                api_start_time = time.time()
                success = await self._translate_with_retry(
                    word=word,
                    from_lang=source_lang,
                    to_lang=target_lang,
                    user_native=native_language,
                    user_learning=(target_lang if native_language == source_lang else source_lang),
                )
                api_duration = time.time() - api_start_time

                if success:
                    stats["processed"] += 1
                    await circuit_breaker.record_success()
                    rate_limiter.record_success()

                    if self.performance_monitor:
                        await self.performance_monitor.record_api_call(api_duration)

                    logger.debug(f"Successfully translated '{word}' ({direction})")
                    return True, "processed"
                else:
                    stats["errors"] += 1
                    await circuit_breaker.record_failure()
                    rate_limiter.record_error()
                    return False, "translation_failed"

            except Exception as e:
                error_type = ErrorClassifier.classify_error(e)
                stats["errors"] += 1
                stats[f"error_{error_type.lower()}"] += 1
                await circuit_breaker.record_failure()
                rate_limiter.record_error()

                if self.performance_monitor:
                    await self.performance_monitor.record_error(error_type)

                logger.error(f"Translation failed for '{word}' ({direction}): {e}")
                return False, error_type

    async def translate_word_parallel(
        self,
        word_entry: Dict,
        from_lang: str,
        to_lang: str,
        user_native: str,
        user_learning: str,
        semaphore: asyncio.Semaphore,
        rate_limiter: TokenBucketRateLimiter,
        circuit_breaker: CircuitBreaker,
        stats: Dict,
    ) -> Tuple[bool, Optional[str]]:
        """Translate a single word with full parallel processing support."""

        async with semaphore:  # Limit concurrency
            word = word_entry["word"]

            try:
                # Check circuit breaker
                if await circuit_breaker.is_open():
                    stats["errors"] += 1
                    return False, "circuit_breaker_open"

                # Rate limiting
                await rate_limiter.acquire()

                # Record performance metrics
                if self.performance_monitor:
                    await self.performance_monitor.record_cache_miss()

                # Check cache first
                if await self.check_word_exists(word, from_lang, to_lang, user_learning):
                    stats["skipped"] += 1
                    if self.performance_monitor:
                        await self.performance_monitor.record_cache_hit()
                    return True, "skipped"

                # Translate with retry logic
                api_start_time = time.time()
                success = await self._translate_with_retry(word, from_lang, to_lang, user_native, user_learning)
                api_duration = time.time() - api_start_time

                if success:
                    stats["processed"] += 1
                    await circuit_breaker.record_success()
                    rate_limiter.record_success()

                    if self.performance_monitor:
                        await self.performance_monitor.record_api_call(api_duration)

                    return True, "processed"
                else:
                    stats["errors"] += 1
                    await circuit_breaker.record_failure()
                    rate_limiter.record_error()
                    return False, "translation_failed"

            except Exception as e:
                error_type = ErrorClassifier.classify_error(e)
                stats["errors"] += 1
                stats[f"error_{error_type.lower()}"] += 1
                await circuit_breaker.record_failure()
                rate_limiter.record_error()

                if self.performance_monitor:
                    await self.performance_monitor.record_error(error_type)

                logger.error(f"Translation failed for '{word}': {e}")
                return False, error_type

    async def process_batch_parallel(
        self,
        batch: List[Dict],
        from_lang: str,
        to_lang: str,
        user_native: str,
        user_learning: str,
        batch_index: int,
    ) -> Dict:
        """Process a batch of words with parallel translation."""

        batch_start_time = time.time()

        # Initialize parallel processing components
        semaphore = asyncio.Semaphore(self.max_concurrent)
        rate_limiter = TokenBucketRateLimiter(
            rate=self.requests_per_second,
            burst=self.max_concurrent,
            adaptive=self.adaptive_rate,
        )
        circuit_breaker = CircuitBreaker() if self.circuit_breaker_enabled else None

        # Statistics tracking
        stats = {
            "processed": 0,
            "skipped": 0,
            "errors": 0,
            "error_rate_limit": 0,
            "error_api_error": 0,
            "error_timeout": 0,
            "error_network": 0,
            "error_parse_error": 0,
            "error_unknown": 0,
        }

        # Create parallel translation tasks
        tasks = []
        for word_entry in batch:
            task = asyncio.create_task(
                self.translate_word_parallel(
                    word_entry,
                    from_lang,
                    to_lang,
                    user_native,
                    user_learning,
                    semaphore,
                    rate_limiter,
                    circuit_breaker or CircuitBreaker(),
                    stats,
                )
            )
            tasks.append(task)

        # Execute all tasks concurrently with progress tracking
        results = []
        completed = 0

        # Process tasks as they complete
        for coro in asyncio.as_completed(tasks):
            try:
                result = await coro
                results.append(result)
                completed += 1

                # Log progress every 10 completions
                if completed % 10 == 0:
                    progress = completed / len(tasks) * 100
                    logger.info(f"Batch {batch_index}: {progress:.1f}% complete ({completed}/{len(tasks)})")

            except Exception as e:
                logger.error(f"Task failed in batch {batch_index}: {e}")
                results.append((False, "task_failed"))
                stats["errors"] += 1

        # Calculate batch statistics
        batch_duration = time.time() - batch_start_time
        throughput = len(batch) / batch_duration if batch_duration > 0 else 0

        batch_stats = {
            "batch_index": batch_index,
            "total_words": len(batch),
            "duration": batch_duration,
            "throughput": throughput,
            "concurrent_tasks": self.max_concurrent,
            **stats,
        }

        logger.info(
            f"Batch {batch_index} completed: {stats['processed']} processed, "
            f"{stats['skipped']} skipped, {stats['errors']} errors "
            f"in {batch_duration:.1f}s ({throughput:.1f} words/s)"
        )

        return batch_stats

    async def process_language_pair(
        self,
        from_lang: str,
        to_lang: str,
        word_lists: Dict[str, List[Dict]],
        checkpoint_data: Optional[Dict] = None,
    ) -> Dict:
        """Process all words for a specific language pair."""
        pair_key = f"{from_lang}-{to_lang}"
        logger.info(f"Processing language pair: {pair_key}")

        # Get word list for source language
        if from_lang not in word_lists:
            logger.error(f"No word list available for source language: {from_lang}")
            return {
                "pair": pair_key,
                "status": "failed",
                "error": f"No word list for {from_lang}",
                "processed": 0,
                "skipped": 0,
                "errors": 0,
            }

        # Determine the native language for this language pair
        # For pairs like "russian-english", Russian should be the native language
        # For pairs like "english-russian", Russian should still be the native language
        native_language = self._determine_native_language(from_lang, to_lang)

        # Get both word lists for bidirectional processing
        source_words = word_lists.get(from_lang, [])
        target_words = word_lists.get(to_lang, [])

        if not source_words and not target_words:
            logger.error(f"No word lists available for either {from_lang} or {to_lang}")
            return {
                "pair": pair_key,
                "status": "failed",
                "error": f"No word lists for {from_lang} or {to_lang}",
                "processed": 0,
                "skipped": 0,
                "errors": 0,
            }

        # Create combined processing plan for bidirectional translation
        processing_plan = []

        # Add source language words (from_lang -> to_lang)
        if source_words:
            for word_entry in source_words:
                processing_plan.append(
                    {
                        "word_entry": word_entry,
                        "source_lang": from_lang,
                        "target_lang": to_lang,
                        "native_lang": native_language,
                        "direction": f"{from_lang}->{to_lang}",
                    }
                )

        # Add target language words (to_lang -> from_lang)
        if target_words:
            for word_entry in target_words:
                processing_plan.append(
                    {
                        "word_entry": word_entry,
                        "source_lang": to_lang,
                        "target_lang": from_lang,
                        "native_lang": native_language,
                        "direction": f"{to_lang}->{from_lang}",
                    }
                )

        total_words = len(processing_plan)
        logger.info(
            f"Bidirectional processing plan: {len(source_words)} {from_lang} words + {len(target_words)} {to_lang} words = {total_words} total translations"
        )

        # Resume from checkpoint if available (with bidirectional migration support)
        start_index = 0
        if checkpoint_data and pair_key in checkpoint_data.get("pairs", {}):
            old_index = checkpoint_data["pairs"][pair_key].get("last_processed_index", 0)

            # Check if this is an old unidirectional checkpoint
            if old_index >= len(source_words) - 1 and len(target_words) > 0:
                # Old checkpoint completed source words, start from target words
                start_index = len(source_words)
                logger.info(f"Migrating from old unidirectional checkpoint. Completed {len(source_words)} {from_lang} words.")
                logger.info(f"Starting English→Russian translations from index {start_index}")
            else:
                start_index = old_index + 1
                logger.info(f"Resuming from word index {start_index}")

        # Statistics for this pair
        processed = 0
        skipped = 0
        errors = 0

        # Initialize parallel processing components
        if self.performance_monitoring:
            self.performance_monitor = PerformanceMonitor()

        if total_words > 0:
            self.progress_tracker = ParallelProgressTracker(total_words)

        # Process words in batches with parallel processing (bidirectional)
        for i in range(start_index, total_words, self.batch_size):
            if self.shutdown_requested:
                logger.info("Shutdown requested, stopping processing")
                break

            batch_end = min(i + self.batch_size, total_words)
            batch_plan = processing_plan[i:batch_end]
            batch_index = i // self.batch_size + 1

            logger.info(f"Processing batch {batch_index}: translations {i + 1}-{batch_end} of {total_words} (bidirectional parallel mode)")

            # Process batch with parallel translation (bidirectional)
            batch_stats = await self.process_batch_parallel_bidirectional(batch_plan, native_language, batch_index)

            # Update overall statistics
            processed += batch_stats["processed"]
            skipped += batch_stats["skipped"]
            errors += batch_stats["errors"]

            self.total_words_processed += batch_stats["processed"]
            self.total_words_skipped += batch_stats["skipped"]
            self.total_errors += batch_stats["errors"]

            # Update progress tracker
            if self.progress_tracker:
                await self.progress_tracker.update(
                    processed=batch_stats["processed"],
                    skipped=batch_stats["skipped"],
                    errors=batch_stats["errors"],
                )

            # Save checkpoint after each batch
            current_index = batch_end - 1
            checkpoint_data_new = {
                "timestamp": datetime.now().isoformat(),
                "pairs": {
                    pair_key: {
                        "last_processed_index": current_index,
                        "processed": processed,
                        "skipped": skipped,
                        "errors": errors,
                    }
                },
            }
            self.save_checkpoint(f"populate_{pair_key}", checkpoint_data_new)

            # Calculate batch performance metrics
            batch_throughput = batch_stats["throughput"]
            remaining_words = total_words - batch_end
            eta_seconds = remaining_words / batch_throughput if batch_throughput > 0 else 0
            eta_minutes = eta_seconds / 60

            logger.info(f"Batch {batch_index} performance: {batch_throughput:.1f} words/s")
            logger.info(f"Overall progress: {batch_end}/{total_words} ({batch_end / total_words * 100:.1f}%) - ETA: {eta_minutes:.1f} minutes")
            logger.info(f"Cumulative stats: {processed} processed, {skipped} skipped, {errors} errors")

        # Final statistics for this pair
        result = {
            "pair": pair_key,
            "status": "completed" if not self.shutdown_requested else "interrupted",
            "total_words": total_words,
            "processed": processed,
            "skipped": skipped,
            "errors": errors,
            "success_rate": (processed / (processed + errors) * 100 if (processed + errors) > 0 else 0),
        }

        logger.info(f"Language pair {pair_key} completed: {processed} processed, {skipped} skipped, {errors} errors")
        return result

    async def populate_database(self, language_pairs: List[Tuple[str, str]], resume: bool = False) -> Dict:
        """Main method to populate the database with all language pairs."""
        logger.info("Starting database population...")
        self.start_time = time.time()

        # Load word lists
        word_lists = await self.load_word_lists()
        if not word_lists:
            raise ValueError("No word lists found. Please run generate_word_lists.py first.")

        # Load checkpoint if resuming (with bidirectional migration support)
        main_checkpoint_data = None
        completed_pairs = set()
        if resume:
            main_checkpoint_data = self.load_checkpoint("populate_main")
            if main_checkpoint_data:
                raw_completed_pairs = set(main_checkpoint_data.get("completed_pairs", []))

                # Check each "completed" pair for bidirectional migration needs
                for pair in raw_completed_pairs:
                    from_lang, to_lang = pair.split("-", 1)

                    # Check if this pair needs bidirectional migration
                    source_words = word_lists.get(from_lang, [])
                    target_words = word_lists.get(to_lang, [])

                    # Load pair-specific checkpoint to check completion status
                    pair_checkpoint = self.load_checkpoint(f"populate_{pair}")
                    if pair_checkpoint and pair in pair_checkpoint.get("pairs", {}):
                        last_index = pair_checkpoint["pairs"][pair].get("last_processed_index", 0)
                        total_bidirectional = len(source_words) + len(target_words)

                        # If last_index suggests only unidirectional processing was done
                        if last_index < total_bidirectional - 1 and len(target_words) > 0:
                            logger.info(f"Pair '{pair}' needs bidirectional migration - removing from completed list")
                            continue  # Don't add to completed_pairs

                    completed_pairs.add(pair)

                logger.info(f"Resuming from checkpoint. Completed pairs: {completed_pairs}")

        # Process each language pair
        results = {}

        for from_lang, to_lang in language_pairs:
            pair_key = f"{from_lang}-{to_lang}"

            # Skip if this pair was already completed
            if pair_key in completed_pairs:
                logger.info(f"Skipping already completed pair: {pair_key}")
                continue
            if self.shutdown_requested:
                logger.info("Shutdown requested, stopping processing")
                break

            # Load pair-specific checkpoint data
            pair_checkpoint_data = None
            if resume:
                pair_checkpoint_data = self.load_checkpoint(f"populate_{pair_key}")
                if pair_checkpoint_data:
                    logger.info(f"Loaded checkpoint for pair {pair_key}")

            pair_result = await self.process_language_pair(from_lang, to_lang, word_lists, pair_checkpoint_data)
            results[f"{from_lang}-{to_lang}"] = pair_result

            # Save main checkpoint
            main_checkpoint = {
                "timestamp": datetime.now().isoformat(),
                "completed_pairs": list(results.keys()),
                "total_processed": self.total_words_processed,
                "total_skipped": self.total_words_skipped,
                "total_errors": self.total_errors,
            }
            self.save_checkpoint("populate_main", main_checkpoint)

        # Calculate overall statistics
        total_duration = time.time() - self.start_time

        overall_stats = {
            "start_time": datetime.fromtimestamp(self.start_time).isoformat(),
            "end_time": datetime.now().isoformat(),
            "duration_seconds": total_duration,
            "duration_minutes": total_duration / 60,
            "total_pairs_processed": len(results),
            "total_words_processed": self.total_words_processed,
            "total_words_skipped": self.total_words_skipped,
            "total_errors": self.total_errors,
            "overall_success_rate": (
                self.total_words_processed / (self.total_words_processed + self.total_errors) * 100
                if (self.total_words_processed + self.total_errors) > 0
                else 0
            ),
            "pairs": results,
        }

        return overall_stats

    def generate_report(self, stats: Dict) -> str:
        """Generate a comprehensive report of the database population."""
        report_filename = f"database_population_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        report_path = self.reports_dir / report_filename

        try:
            with open(report_path, "w", encoding="utf-8") as f:
                f.write("Database Population Report\n")
                f.write("=" * 50 + "\n\n")

                f.write(f"Start Time: {stats['start_time']}\n")
                f.write(f"End Time: {stats['end_time']}\n")
                f.write(f"Duration: {stats['duration_minutes']:.1f} minutes\n\n")

                # Add parallel processing configuration
                f.write("Processing Configuration:\n")
                f.write("-" * 25 + "\n")
                f.write(f"Max concurrent tasks: {self.max_concurrent}\n")
                f.write(f"Requests per second: {self.requests_per_second}\n")
                f.write(f"Adaptive rate limiting: {self.adaptive_rate}\n")
                f.write(f"Circuit breaker enabled: {self.circuit_breaker_enabled}\n")
                f.write(f"Performance monitoring: {self.performance_monitoring}\n\n")

                f.write("Overall Statistics:\n")
                f.write("-" * 20 + "\n")
                f.write(f"Language pairs processed: {stats['total_pairs_processed']}\n")
                f.write(f"Words processed: {stats['total_words_processed']}\n")
                f.write(f"Words skipped (already existed): {stats['total_words_skipped']}\n")
                f.write(f"Errors: {stats['total_errors']}\n")
                f.write(f"Overall success rate: {stats['overall_success_rate']:.1f}%\n")

                # Add performance metrics if available
                if self.performance_monitor:
                    perf_summary = self.performance_monitor.get_summary()
                    f.write(f"Average API latency: {perf_summary['avg_api_latency']:.3f}s\n")
                    f.write(f"Cache hit rate: {perf_summary['cache_hit_rate']:.1%}\n")
                    f.write(f"Total API calls: {perf_summary['api_calls']}\n")

                f.write("\n")

                f.write("Language Pair Details:\n")
                f.write("-" * 25 + "\n")

                for pair_key, pair_stats in stats["pairs"].items():
                    f.write(f"\n{pair_key.upper()}:\n")
                    f.write(f"  Status: {pair_stats['status']}\n")
                    f.write(f"  Total words: {pair_stats['total_words']}\n")
                    f.write(f"  Processed: {pair_stats['processed']}\n")
                    f.write(f"  Skipped: {pair_stats['skipped']}\n")
                    f.write(f"  Errors: {pair_stats['errors']}\n")
                    f.write(f"  Success rate: {pair_stats['success_rate']:.1f}%\n")

                f.write(f"\nDatabase population completed!\n")
                f.write(f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

            logger.info(f"Report saved to {report_path}")
            return str(report_path)

        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
            return ""


async def run_population(
    all_pairs: bool,
    pairs: Optional[str],
    resume: bool,
    batch_size: int,
    delay: float,
    max_retries: int,
    checkpoint_interval: int,
    verbose: bool,
    max_concurrent: int,
    requests_per_second: float,
    adaptive_rate: bool,
    circuit_breaker: bool,
    batch_db_writes: bool,
    performance_monitoring: bool,
    sequential: bool,
    source: str,
    db_languages: List[str],
):
    """Core population logic separated from CLI."""

    if verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Determine which language pairs to process
    if all_pairs:
        language_pairs = None  # Will use all pairs
    elif pairs:
        language_pairs = pairs
    else:
        click.echo("Error: Must specify either --all-pairs or --pairs", err=True)
        return 1

    # Initialize populator
    populator = DatabasePopulator()

    # Override configuration
    populator.batch_size = batch_size
    populator.rate_limit_delay = delay
    populator.max_retries = max_retries
    populator.checkpoint_interval = checkpoint_interval

    # Configure parallel processing settings
    populator.max_concurrent = max_concurrent
    populator.requests_per_second = requests_per_second
    populator.adaptive_rate = adaptive_rate
    populator.circuit_breaker_enabled = circuit_breaker
    populator.batch_db_writes = batch_db_writes
    # Configure word source settings
    populator.word_source = source
    populator.db_languages = db_languages

    # Log word source configuration
    logger.info("Word source configuration:")
    logger.info(f"  Source: {populator.word_source}")
    if populator.db_languages:
        logger.info(f"  Database languages: {', '.join(populator.db_languages)}")
    populator.performance_monitoring = performance_monitoring

    # Log parallel processing configuration
    if not sequential:
        logger.info("Parallel processing configuration:")
        logger.info(f"  Max concurrent tasks: {populator.max_concurrent}")
        logger.info(f"  Requests per second: {populator.requests_per_second}")
        logger.info(f"  Adaptive rate limiting: {populator.adaptive_rate}")
        logger.info(f"  Circuit breaker: {populator.circuit_breaker_enabled}")
        logger.info(f"  Batch DB writes: {populator.batch_db_writes}")
        logger.info(f"  Performance monitoring: {populator.performance_monitoring}")
    else:
        logger.info("Using sequential processing mode")
        populator.max_concurrent = 1
        populator.adaptive_rate = False
        populator.circuit_breaker_enabled = False

    try:
        # Initialize connections
        await populator.initialize()

        # Get language pairs to process
        pairs_to_process = populator.get_language_pairs(language_pairs)

        if not pairs_to_process:
            logger.error("No valid language pairs specified")
            return 1

        logger.info(f"Will process {len(pairs_to_process)} language pairs:")
        for from_lang, to_lang in pairs_to_process:
            logger.info(f"  {from_lang} -> {to_lang}")

        # Populate database
        stats = await populator.populate_database(pairs_to_process, resume)

        # Generate report
        report_path = populator.generate_report(stats)

        # Print summary
        click.echo("\n" + "=" * 60)
        click.echo("DATABASE POPULATION SUMMARY")
        click.echo("=" * 60)

        click.echo(f"Duration: {stats['duration_minutes']:.1f} minutes")
        click.echo(f"Language pairs processed: {stats['total_pairs_processed']}")
        click.echo(f"Words processed: {stats['total_words_processed']}")
        click.echo(f"Words skipped: {stats['total_words_skipped']}")
        click.echo(f"Errors: {stats['total_errors']}")
        click.echo(f"Overall success rate: {stats['overall_success_rate']:.1f}%")

        if report_path:
            click.echo(f"Report saved: {report_path}")

        return 0 if stats["total_errors"] == 0 else 1

    except Exception as e:
        logger.error(f"Database population failed: {e}")
        return 1

    finally:
        # Clean up
        await populator.cleanup()


@click.command()
@click.option("--all-pairs", is_flag=True, help="Process all possible language pairs")
@click.option(
    "--pairs",
    type=str,
    help="Comma-separated list of language pairs (e.g., english-polish,polish-english)",
)
@click.option("--resume", is_flag=True, help="Resume from the last checkpoint")
@click.option(
    "--batch-size",
    type=int,
    default=50,
    help="Number of words to process in each batch",
)
@click.option(
    "--delay",
    type=float,
    default=1.0,
    help="Delay in seconds between API calls (legacy, use --requests-per-second instead)",
)
@click.option(
    "--max-retries",
    type=int,
    default=3,
    help="Maximum number of retries for failed translations",
)
@click.option("--checkpoint-interval", type=int, default=100, help="Save checkpoint every N words")
@click.option("--verbose", is_flag=True, help="Enable verbose logging")
@click.option(
    "--max-concurrent",
    type=int,
    default=25,
    help="Maximum number of concurrent translation tasks",
)
@click.option(
    "--requests-per-second",
    type=float,
    default=50.0,
    help="Maximum requests per second for rate limiting",
)
@click.option(
    "--adaptive-rate",
    is_flag=True,
    help="Enable adaptive rate limiting based on API response patterns",
)
@click.option(
    "--circuit-breaker",
    is_flag=True,
    help="Enable circuit breaker pattern for API failure protection",
)
@click.option(
    "--batch-db-writes",
    is_flag=True,
    help="Enable batch database writes for improved performance",
)
@click.option(
    "--performance-monitoring",
    is_flag=True,
    help="Enable detailed performance monitoring and metrics",
)
@click.option(
    "--sequential",
    is_flag=True,
    help="Use sequential processing instead of parallel (for debugging)",
)
@click.option(
    "--source",
    type=click.Choice(["files", "database", "mixed"]),
    default="files",
    help="Source for word lists: files (JSON), database (existing words), or mixed (both)",
)
@click.option(
    "--db-languages",
    default="russian,english",
    type=str,
    help="Comma-separated list of languages to fetch from database (e.g., russian,english)",
)
@click.option(
    "--show-stats",
    is_flag=True,
    help="Show word count statistics from database and exit",
)
def main(
    all_pairs: bool,
    pairs: Optional[str],
    resume: bool,
    batch_size: int,
    delay: float,
    max_retries: int,
    checkpoint_interval: int,
    verbose: bool,
    max_concurrent: int,
    requests_per_second: float,
    adaptive_rate: bool,
    circuit_breaker: bool,
    batch_db_writes: bool,
    performance_monitoring: bool,
    sequential: bool,
    source: str,
    db_languages: Optional[str],
    show_stats: bool,
):
    """
    Populate database with word translations for all language pairs.

    This script provides high-performance parallel translation processing
    with intelligent rate limiting, error handling, and progress monitoring.

    Examples:

        # Process all language pairs with default parallel settings
        python scripts/populate_database.py --all-pairs

        # Process specific pairs with high performance
        python scripts/populate_database.py --pairs english-polish,polish-english --max-concurrent 50

        # Use database words for Russian and English (cost-optimized)
        python scripts/populate_database.py --source database --db-languages russian,english --all-pairs

        # Mixed mode: database for some languages, files for others
        python scripts/populate_database.py --source mixed --db-languages russian,english --pairs russian-polish,english-spanish

        # Show database word statistics
        python scripts/populate_database.py --show-stats

        # Conservative processing with circuit breaker
        python scripts/populate_database.py --pairs russian-english --max-concurrent 10 --circuit-breaker

        # Resume from checkpoint with monitoring
        python scripts/populate_database.py --resume --performance-monitoring
    """

    # Validate arguments
    if not all_pairs and not pairs:
        click.echo("Error: Must specify either --all-pairs or --pairs", err=True)
        raise click.Abort()

    if all_pairs and pairs:
        click.echo("Error: Cannot specify both --all-pairs and --pairs", err=True)
        raise click.Abort()
    # Parse database languages if provided
    parsed_db_languages = []
    if db_languages:
        parsed_db_languages = [lang.strip().lower() for lang in db_languages.split(",")]
        logger.info(f"Database languages specified: {parsed_db_languages}")

    # Handle show-stats option
    if show_stats:
        # Just show statistics and exit
        async def show_stats_only():
            populator = DatabasePopulator()
            try:
                await populator.initialize()
                await populator.show_database_statistics()
                return 0
            except Exception as e:
                logger.error(f"Failed to show statistics: {e}")
                return 1
            finally:
                await populator.cleanup()

        exit_code = asyncio.run(show_stats_only())
        sys.exit(exit_code)

    # Validate database source parameters
    if source in ["database", "mixed"] and not parsed_db_languages:
        click.echo(
            "Error: --db-languages must be specified when using database or mixed source",
            err=True,
        )
        raise click.Abort()

    # Run the population process
    exit_code = asyncio.run(
        run_population(
            all_pairs=all_pairs,
            pairs=pairs,
            resume=resume,
            batch_size=batch_size,
            delay=delay,
            max_retries=max_retries,
            checkpoint_interval=checkpoint_interval,
            verbose=verbose,
            max_concurrent=max_concurrent,
            requests_per_second=requests_per_second,
            adaptive_rate=adaptive_rate,
            circuit_breaker=circuit_breaker,
            batch_db_writes=batch_db_writes,
            performance_monitoring=performance_monitoring,
            sequential=sequential,
            source=source,
            db_languages=parsed_db_languages,
        )
    )

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
