"""Add RAG tables: conversation_messages, user_facts, user_profile_summaries

Revision ID: 0cb2e933ba60
Revises: 80f8c0df2e01
Create Date: 2025-09-01 00:18:07.757882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb2e933ba60'
down_revision: Union[str, None] = '80f8c0df2e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
