"""Update user_facts embedding dimension to 384

Revision ID: ed964017b907
Revises: 0cb2e933ba60
Create Date: 2025-09-01 00:22:26.178192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'ed964017b907'
down_revision: Union[str, None] = '0cb2e933ba60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_facts', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_facts', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###
