/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConversationMessage } from './conversation-message';

/**
 * Conversation history schema.
 * @export
 * @interface ConversationHistory
 */
export interface ConversationHistory {
    /**
     * User ID
     * @type {number}
     * @memberof ConversationHistory
     */
    'user_id': number;
    /**
     * List of messages
     * @type {Array<ConversationMessage>}
     * @memberof ConversationHistory
     */
    'messages': Array<ConversationMessage>;
    /**
     * Total message count
     * @type {number}
     * @memberof ConversationHistory
     */
    'total_messages': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ConversationHistory
     */
    'date_range'?: { [key: string]: string; } | null;
}

