/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to process a conversation message.
 * @export
 * @interface ConversationRequest
 */
export interface ConversationRequest {
    /**
     * User ID
     * @type {number}
     * @memberof ConversationRequest
     */
    'user_id': number;
    /**
     * Message text
     * @type {string}
     * @memberof ConversationRequest
     */
    'message': string;
    /**
     * Whether this is from voice
     * @type {boolean}
     * @memberof ConversationRequest
     */
    'is_voice'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConversationRequest
     */
    'context'?: { [key: string]: any; } | null;
}

