/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EmotionType } from './emotion-type';
// May contain unused imports in some cases
// @ts-ignore
import type { MessageRole } from './message-role';

/**
 * Conversation message schema.
 * @export
 * @interface ConversationMessage
 */
export interface ConversationMessage {
    /**
     * Creation timestamp
     * @type {string}
     * @memberof ConversationMessage
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMessage
     */
    'updated_at'?: string | null;
    /**
     * Message ID
     * @type {number}
     * @memberof ConversationMessage
     */
    'id': number;
    /**
     * User ID
     * @type {number}
     * @memberof ConversationMessage
     */
    'user_id': number;
    /**
     * Message role
     * @type {MessageRole}
     * @memberof ConversationMessage
     */
    'role': MessageRole;
    /**
     * 
     * @type {string}
     * @memberof ConversationMessage
     */
    'message_text'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConversationMessage
     */
    'transcribed_text'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ConversationMessage
     */
    'sentiment_score'?: number | null;
    /**
     * 
     * @type {EmotionType}
     * @memberof ConversationMessage
     */
    'emotion'?: EmotionType | null;
    /**
     * Whether this was a voice message
     * @type {boolean}
     * @memberof ConversationMessage
     */
    'is_voice'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ConversationMessage
     */
    'metadata'?: { [key: string]: any; } | null;
}



