/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Detected emotion types.
 * @export
 * @enum {string}
 */

export const EmotionType = {
    Neutral: 'neutral',
    Happy: 'happy',
    Sad: 'sad',
    Angry: 'angry',
    Surprised: 'surprised',
    Fearful: 'fearful',
    Disgusted: 'disgusted'
} as const;

export type EmotionType = typeof EmotionType[keyof typeof EmotionType];



