/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EmotionType } from './emotion-type';

/**
 * Emotion analysis result.
 * @export
 * @interface EmotionAnalysis
 */
export interface EmotionAnalysis {
    /**
     * Analyzed text
     * @type {string}
     * @memberof EmotionAnalysis
     */
    'text': string;
    /**
     * Sentiment score
     * @type {number}
     * @memberof EmotionAnalysis
     */
    'sentiment_score': number;
    /**
     * Primary emotion
     * @type {EmotionType}
     * @memberof EmotionAnalysis
     */
    'primary_emotion': EmotionType;
    /**
     * Confidence score
     * @type {number}
     * @memberof EmotionAnalysis
     */
    'confidence': number;
    /**
     * All emotion scores
     * @type {{ [key: string]: number; }}
     * @memberof EmotionAnalysis
     */
    'emotions': { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof EmotionAnalysis
     */
    'voice_tone_suggestion'?: string | null;
}



