/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Schema for searching facts.
 * @export
 * @interface FactSearch
 */
export interface FactSearch {
    /**
     * User ID
     * @type {number}
     * @memberof FactSearch
     */
    'user_id': number;
    /**
     * Search query
     * @type {string}
     * @memberof FactSearch
     */
    'query': string;
    /**
     * Maximum results
     * @type {number}
     * @memberof FactSearch
     */
    'limit'?: number;
    /**
     * Minimum similarity score
     * @type {number}
     * @memberof FactSearch
     */
    'min_similarity'?: number;
}

