/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Schema for creating a fact.
 * @export
 * @interface FactCreate
 */
export interface FactCreate {
    /**
     * User ID
     * @type {number}
     * @memberof FactCreate
     */
    'user_id': number;
    /**
     * Fact text
     * @type {string}
     * @memberof FactCreate
     */
    'fact_text': string;
    /**
     * 
     * @type {string}
     * @memberof FactCreate
     */
    'fact_summary'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FactCreate
     */
    'category'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FactCreate
     */
    'source_message_id'?: number | null;
}

