/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Memory statistics for a user.
 * @export
 * @interface MemoryStats
 */
export interface MemoryStats {
    /**
     * User ID
     * @type {number}
     * @memberof MemoryStats
     */
    'user_id': number;
    /**
     * Total facts stored
     * @type {number}
     * @memberof MemoryStats
     */
    'total_facts': number;
    /**
     * Facts by category
     * @type {{ [key: string]: number; }}
     * @memberof MemoryStats
     */
    'fact_categories': { [key: string]: number; };
    /**
     * Number of profile summaries
     * @type {number}
     * @memberof MemoryStats
     */
    'profile_summaries_count': number;
    /**
     * Memory density score
     * @type {number}
     * @memberof MemoryStats
     */
    'memory_density': number;
    /**
     * 
     * @type {string}
     * @memberof MemoryStats
     */
    'last_fact_date'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MemoryStats
     */
    'storage_size_bytes'?: number | null;
}

