/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FactSearchResult } from './fact-search-result';
// May contain unused imports in some cases
// @ts-ignore
import type { ProfileSummary } from './profile-summary';

/**
 * Complete memory context for a user.
 * @export
 * @interface MemoryContext
 */
export interface MemoryContext {
    /**
     * User ID
     * @type {number}
     * @memberof MemoryContext
     */
    'user_id': number;
    /**
     * Relevant facts
     * @type {Array<FactSearchResult>}
     * @memberof MemoryContext
     */
    'relevant_facts': Array<FactSearchResult>;
    /**
     * Profile summaries
     * @type {Array<ProfileSummary>}
     * @memberof MemoryContext
     */
    'profile_summaries': Array<ProfileSummary>;
    /**
     * Recent conversation messages
     * @type {Array<{ [key: string]: any; }>}
     * @memberof MemoryContext
     */
    'recent_messages': Array<{ [key: string]: any; }>;
    /**
     * Context generation timestamp
     * @type {string}
     * @memberof MemoryContext
     */
    'context_timestamp': string;
}

