/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Message role in conversation.
 * @export
 * @enum {string}
 */

export const MessageRole = {
    User: 'user',
    Assistant: 'assistant',
    System: 'system'
} as const;

export type MessageRole = typeof MessageRole[keyof typeof MessageRole];



