/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Schema for creating/updating profile summary.
 * @export
 * @interface ProfileSummaryCreate
 */
export interface ProfileSummaryCreate {
    /**
     * User ID
     * @type {number}
     * @memberof ProfileSummaryCreate
     */
    'user_id': number;
    /**
     * Summary topic
     * @type {string}
     * @memberof ProfileSummaryCreate
     */
    'summary_topic'?: string;
    /**
     * Force regeneration
     * @type {boolean}
     * @memberof ProfileSummaryCreate
     */
    'force_regenerate'?: boolean;
}

