/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User profile summary schema.
 * @export
 * @interface ProfileSummary
 */
export interface ProfileSummary {
    /**
     * Creation timestamp
     * @type {string}
     * @memberof ProfileSummary
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ProfileSummary
     */
    'updated_at'?: string | null;
    /**
     * Summary ID
     * @type {number}
     * @memberof ProfileSummary
     */
    'id': number;
    /**
     * User ID
     * @type {number}
     * @memberof ProfileSummary
     */
    'user_id': number;
    /**
     * Summary text
     * @type {string}
     * @memberof ProfileSummary
     */
    'summary_text': string;
    /**
     * Summary topic
     * @type {string}
     * @memberof ProfileSummary
     */
    'summary_topic': string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof ProfileSummary
     */
    'last_updated': string;
}

