/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request for text-to-speech synthesis.
 * @export
 * @interface SynthesisRequest
 */
export interface SynthesisRequest {
    /**
     * Text to synthesize
     * @type {string}
     * @memberof SynthesisRequest
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof SynthesisRequest
     */
    'voice'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SynthesisRequest
     */
    'emotion'?: string | null;
    /**
     * Speech speed
     * @type {number}
     * @memberof SynthesisRequest
     */
    'speed'?: number;
    /**
     * 
     * @type {string}
     * @memberof SynthesisRequest
     */
    'language'?: string | null;
}

