/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from text-to-speech synthesis.
 * @export
 * @interface SynthesisResponse
 */
export interface SynthesisResponse {
    /**
     * 
     * @type {string}
     * @memberof SynthesisResponse
     */
    'audio_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SynthesisResponse
     */
    'audio_base64'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SynthesisResponse
     */
    'duration_seconds'?: number | null;
    /**
     * TTS provider used
     * @type {string}
     * @memberof SynthesisResponse
     */
    'provider': string;
    /**
     * Voice used
     * @type {string}
     * @memberof SynthesisResponse
     */
    'voice': string;
}

