/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from voice transcription.
 * @export
 * @interface TranscriptionResponse
 */
export interface TranscriptionResponse {
    /**
     * Transcribed text
     * @type {string}
     * @memberof TranscriptionResponse
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof TranscriptionResponse
     */
    'language'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TranscriptionResponse
     */
    'confidence'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TranscriptionResponse
     */
    'duration_seconds'?: number | null;
}

