/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TTS provider information.
 * @export
 * @interface TTSProvider
 */
export interface TTSProvider {
    /**
     * Provider name
     * @type {string}
     * @memberof TTSProvider
     */
    'name': string;
    /**
     * Available voices
     * @type {Array<{ [key: string]: string; }>}
     * @memberof TTSProvider
     */
    'voices': Array<{ [key: string]: string; }>;
    /**
     * Supported languages
     * @type {Array<string>}
     * @memberof TTSProvider
     */
    'languages': Array<string>;
    /**
     * Provider features
     * @type {{ [key: string]: any; }}
     * @memberof TTSProvider
     */
    'features': { [key: string]: any; };
}

