/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User statistics schema.
 * @export
 * @interface UserStats
 */
export interface UserStats {
    /**
     * User ID
     * @type {number}
     * @memberof UserStats
     */
    'user_id': number;
    /**
     * Total messages sent
     * @type {number}
     * @memberof UserStats
     */
    'total_messages'?: number;
    /**
     * Total voice messages
     * @type {number}
     * @memberof UserStats
     */
    'total_voice_messages'?: number;
    /**
     * Total facts stored
     * @type {number}
     * @memberof UserStats
     */
    'total_facts'?: number;
    /**
     * Number of profile summaries
     * @type {number}
     * @memberof UserStats
     */
    'profile_summaries'?: number;
    /**
     * Memory density score
     * @type {number}
     * @memberof UserStats
     */
    'memory_density'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserStats
     */
    'last_active'?: string | null;
}

