/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User fact schema.
 * @export
 * @interface UserFact
 */
export interface UserFact {
    /**
     * Creation timestamp
     * @type {string}
     * @memberof UserFact
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof UserFact
     */
    'updated_at'?: string | null;
    /**
     * Fact ID
     * @type {number}
     * @memberof UserFact
     */
    'id': number;
    /**
     * User ID
     * @type {number}
     * @memberof UserFact
     */
    'user_id': number;
    /**
     * Fact text
     * @type {string}
     * @memberof UserFact
     */
    'fact_text': string;
    /**
     * 
     * @type {string}
     * @memberof UserFact
     */
    'fact_summary'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserFact
     */
    'source_message_id'?: number | null;
    /**
     * Fact confidence
     * @type {number}
     * @memberof UserFact
     */
    'confidence'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserFact
     */
    'category'?: string | null;
}

