/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Complete user schema.
 * @export
 * @interface User
 */
export interface User {
    /**
     * Creation timestamp
     * @type {string}
     * @memberof User
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updated_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'first_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_name'?: string | null;
    /**
     * User language code
     * @type {string}
     * @memberof User
     */
    'language'?: string;
    /**
     * User ID
     * @type {number}
     * @memberof User
     */
    'user_id': number;
    /**
     * User active status
     * @type {boolean}
     * @memberof User
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof User
     */
    'metadata'?: { [key: string]: any; } | null;
}

