/* tslint:disable */
/* eslint-disable */
/**
 * Privet API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Complete voice processing response.
 * @export
 * @interface VoiceProcessingResponse
 */
export interface VoiceProcessingResponse {
    /**
     * Transcribed text
     * @type {string}
     * @memberof VoiceProcessingResponse
     */
    'transcribed_text': string;
    /**
     * AI response text
     * @type {string}
     * @memberof VoiceProcessingResponse
     */
    'response_text': string;
    /**
     * 
     * @type {string}
     * @memberof VoiceProcessingResponse
     */
    'audio_url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VoiceProcessingResponse
     */
    'emotion_detected'?: string | null;
    /**
     * Number of facts extracted
     * @type {number}
     * @memberof VoiceProcessingResponse
     */
    'facts_extracted'?: number;
    /**
     * Total processing time
     * @type {number}
     * @memberof VoiceProcessingResponse
     */
    'processing_time_ms': number;
}

